### PR TITLE
#758 - XeWhen must accept the third argument

### PR DESCRIPTION
**Pull request by neonailol**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#759` is now in scope, role is `REV`.

**Comment by yegor256** [comment]
@neonailol looks good, but we still need previous constructors :) Don't delete them, they must stay, but must return empty XeSources.

**Comment by neonailol** [comment]
@yegor256 Ok, returned previous constructors, and added empty result for negative condition

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#759` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#759` is now out of scope.

**Pull request merged**
