### PR TITLE
For #725: Move header names from BkBasic to public constants

### PR DESCRIPTION
**Pull request by paulodamaso**
For #725:
- Moved fields to public constants in `FkBasic`
- Removed todo in `FkBasicTest`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#853](https://github.com/yegor256/takes/issues/853) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (21 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#853](https://github.com/yegor256/takes/issues/853) is now out of scope

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
> The code reviewer found at least three problems in the code 

Please, confirm that you will try to find at least three issues next time.

**Comment by g4s8** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
