### PR TITLE
README document

### PR DESCRIPTION
**Pull request by Tertioptus**
Just a minor grammatical error in the README document, as well as a literary suggestion.

### CODE REVIEW

**Comment by davvd** [comment]
@tertioptus Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@Tertioptus thanks!

**Comment by davvd** [comment]
@yegor256 I added **16 mins** to your account, many thanks for working with the project (000-1c636a5c)! The completion time here was 14 hours and 8 mins.

extra minutes for review comments (c=1)

+16 added to your rating, at the moment it is: [+4547](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
