### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by davvd** [comment]
@valery1707 Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@valery1707 thanks!

**Comment by davvd** [comment]
@yegor256 I added **16 mins** to your account, many thanks for working with the project (000-b6fd261a)! The completion time here was 18 hours and 56 mins.... extra minutes for review comments (c=1)... +16 to your rating, your total score is [+5165](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
