### PR TITLE
#692 AvoidDuplicateLiterals suppression

### PR DESCRIPTION
**Pull request by xupyprmv**
#692 I removed AvoidDuplicateLiterals warning suppression.

### CODE REVIEW

**Comment by davvd** [comment]
@xupyprmv Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@yegor256 the PR is rather short, please review it

**Comment by xupyprmv** [comment]
@yegor256 Please, review this PR.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@yegor256 Thanks for your contribution, **16 mins** was added to your account, payment ID is `000-354addef`, 70 hours and 17 mins spent total

you're getting extra minutes here (c=1)

+16 added to your rating, current score is: [+208](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
