### PR TITLE
#450 - RsXSLT.InClasspath resolve() method was not using "base" parameter.

### PR DESCRIPTION
**Pull request by danff**
Fix for issue #450 - base parameter in RsXSLT.InClasspath.resolve(String, String) is unused.

- RsXSLT.InClasspath.resolve() method updated to use URI.resolve() for "href" when "base" parameters is not null. When "base" is null URI on href is created.
- RsXSLTTest.resolvesInClasspath() test method updated to test also xsl:include and xsl:import with relative and absolute paths.
- Added 3 .xsl files in order to test InClasspath.resolve() calls also for xsl:include & xsl:import.

### CODE REVIEW

**Comment by davvd** [comment]
@danff Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@dmzaytsev please review, thanks

**Comment by dmzaytsev** [comment]
@danff please update the pull request description

>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

see http://at.teamed.io/qa.html

**Comment by danff** [comment]
@dmzaytsev Title fixed and description updated

**Comment by dmzaytsev** [comment]
@danff thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by danff** [comment]
@dmzaytsev @yegor256 is it possible for me to fix that? and how if yes?

**Comment by dmzaytsev** [comment]
@danff I think it's a temporary issue

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by danff** [comment]
@dmzaytsev @yegor256 any progress with merging?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by elenavolokhova** [comment]
@dmzaytsev 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@dmzaytsev added 10 mins to @elenavolokhova, for QA review, payment code is `72994189`. **21 mins** was added to your account, many thanks for your contribution (payment 72994196)! The task took 70 hours and 25 mins.. you're getting extra minutes here (c=6). +21 added to your rating, current score is: [+1143](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
