### PR TITLE
Issue #678 fix. Remove warning. Use qulice 0.16.4

### PR DESCRIPTION
**Pull request by xupyprmv**
Issue #678. 
I removed warning, switched Qulice to version 0.16.4, added excludes to `pom.xml` to temporary ignore warnings that rises with new version of CheckStyle and PMD. Also I fixed FindBugs warnings and added 2 new puzzles.

### CODE REVIEW

**Comment by davvd** [comment]
@xupyprmv Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@yegor256 the PR is rather short, please review it

**Comment by xupyprmv** [comment]
@yegor256 Please, review this PR.

**Comment by xupyprmv** [comment]
@yegor256 Please, review this pull request.

**Comment by xupyprmv** [comment]
@yegor256 Review this pull request, please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@yegor256 I just added **16 mins** to your account, many thanks for your contribution (000-a6fc4ea2).. 284 hours and 41 mins spent here. you're getting extra minutes here (c=1). +16 added to your rating, current score is: [+495](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
