### PR TITLE
For #791: Introduced Expires Interface

### PR DESCRIPTION
**Pull request by paulodamaso**
For #791: Introduce Expires interface
- Created `Expires` interface with `Never, `Hour` and `Date` implementations
- Created tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#844](https://github.com/yegor256/takes/issues/844) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#844](https://github.com/yegor256/takes/issues/844) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2470346812); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256  Codacy is complaining about three issues, `JUnit tests should include assert() or fail()`, but I'm already using `MatchersAssert.assertThat` for assertions. Worst, there are other methods which uses `MatchersAssert.assertThat` and does not trigger the build failure. Is there some way to configure it?

**Comment by paulodamaso** [comment]
@g4s8 please take a look to the changes

**Comment by g4s8** [comment]
@paulodamaso according to [RFC7234](https://tools.ietf.org/html/rfc7234#section-5.3) expires value must support `0` value which represents time in a past:
>    A cache recipient MUST interpret invalid date formats, especially the
   value "0", as representing a time in the past (i.e., "already
   expired").

**Comment by paulodamaso** [comment]
@g4s8 done, please take a look

**Comment by g4s8** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@yegor256 please pay attention to this one

**Comment by paulodamaso** [comment]
@yegor256 ping, the review time is expiring

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (36 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#844](https://github.com/yegor256/takes/issues/844) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
> The code reviewer found at least three problems in the code 

Please, confirm that you will try to find at least three issues next time.

**Comment by g4s8** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
