### PR TITLE
For #820: Removed todo.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #820: Removed todo. The code is already performing equality of bytes in `AbstractHmBody.matchesSafely`.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by paulodamaso** [comment]
@yegor256 please take a look

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#852` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f14b35ef-fddf-431b-816c-8e38e94852ff, thread: AsyncProc-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/takes#852] declared for identity constraint of element "blanks".
```

[0.35.5](https://github.com/zerocracy/farm): CID: [2841959005](https://www.0crat.com/C3FFK3YAY/2841959005), Type: "Close job", Author: "rultor"

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#852` is not assigned, can't get performer

**Pull request merged**
