### PR TITLE
For #808: Move to Java 8.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #808: Move to Java 8.
- Changed `README.md` to reference Java 8
- Added `<jdk.version>1.8</jdk.version>` to `pom.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 please take a look

**Comment by paulodamaso** [comment]
@yegor256 please try again, I think that this time rultor will accept it

**Comment by paulodamaso** [comment]
@yegor256 please take a look, we have a lot of issues depending on this one

**Comment by paulodamaso** [comment]
@yegor256 please merge this one

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#848` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
