### PR TITLE
#656: Added more unit tests to TkProxyTest

### PR DESCRIPTION
**Pull request by essobedo**
Fix for #656 

The goal of this PR is to add more unit tests to TkProxyTest.

### CODE REVIEW

**Comment by davvd** [comment]
@essobedo Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@dmzaytsev it's yours, please review

**Comment by dmzaytsev** [comment]
@essobedo looks good to me, thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by essobedo** [comment]
@yegor256 Could you please check? thx in advance

**Comment by essobedo** [comment]
@yegor256 ping

**Comment by essobedo** [comment]
@yegor256 please review my PR, thx in advance

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by ypshenychka** [comment]
@dmzaytsev 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by dmzaytsev** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@dmzaytsev Thank you.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `84065493`)... Much appreciated! **18 mins** was added to your account, payment ID `84065518`, time spent is 119 hours and 42 mins... review comments (c=3) added as a bonus... added +18 to your rating, now it is equal to [+2128](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
