### PR TITLE
#341 PsGoogle creates incorrect oauth link

### PR DESCRIPTION
**Pull request by adko-pl**
original ticket: #341 
description of changes: replaced `path("o/oauth2/token")` with `path("o").path("oauth2").path("token")` in `org.takes.facets.auth.social.PsTwitter`
@davvd please find a reviewer

### CODE REVIEW

**Comment by davvd** [comment]
@adko-pl Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@adko-pl what about a unit test first?

**Comment by yegor256** [comment]
@adko-pl this PR is outdated, I'm closing it

**Comment by davvd** [comment]
@yegor256 Thanks so much! Your account was topped up for **17 mins** (transaction ID is `000-741605d1`, the task took 2472 hours and 19 mins)... review comments (c=2) added as a bonus... +17 added to your rating, at the moment it is: [+13351](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
