### PR TITLE
#787 Project contains outdated dependencies

### PR DESCRIPTION
**Pull request by neonailol**
Updated dependencies to their latest release versions as of #787

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#833](https://github.com/yegor256/takes/issues/833) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#833](https://github.com/yegor256/takes/issues/833) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/791722301); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by g4s8** [comment]
@neonailol please update PR title according to [Policy §42](http://www.zerocracy.com/policy.html#42):
> Pull request title explains the problem it is fixing;

**Comment by neonailol** [comment]
@g4s8 is this title ok?

**Comment by g4s8** [comment]
@neonailol yes, thanks

**Comment by g4s8** [comment]
@yegor256 I accept

**Comment by yegor256** [comment]
@rultor merge

**Comment by neonailol** [comment]
@yegor256 is it my problem that this does not merge correctly?

**Comment by yegor256** [comment]
@neonailol I think it is, see the log: https://ci.appveyor.com/project/yegor256/takes The dependencies you introduce don't allow it to compile, I believe. Or I'm wrong?

**Comment by neonailol** [comment]
@yegor256 yeah, look's like it's because of appveyor configured to build against Java 7, and travis is built on Java 8, also look's like pretty print format changed for json between this java versions, I will update tests, and appveyor config to use java8

**Comment by neonailol** [comment]
@yegor256 look's like I cant just change appveyor settings, should I revert dependencies, to only supporting Java 7 ones?

**Comment by yegor256** [comment]
@neonailol just make changes to appveyor.yml, most probably to this line: https://github.com/yegor256/takes/blob/master/appveyor.yml#L6

**Comment by neonailol** [comment]
@yegor256 done, also, maybe also add [Maven Wrapper|https://github.com/takari/maven-wrapper], so its version will be consistent across build environments, it is widely used practice

**Comment by yegor256** [comment]
@rultor merge

**Comment by neonailol** [comment]
@yegor256 I found the problem, one of the parent artifacts have old `duplicate-finder-maven-plugin` that false report Java 9 `module-info` classes as duplicates, please upgrade it in the parent project. A new version of `duplicate-finder-maven-plugin` can be found on [github]https://github.com/basepom/duplicate-finder-maven-plugin), notice that the `groupId` for this plugin also changed.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@neonailol would be helpful if you submit a bug report to jcabi/jcabi-parent and I will fix it there and release a new version: https://github.com/jcabi/jcabi-parent

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/833#issuecomment-376402910))

@neonailol It's a code review job [#833](https://github.com/yegor256/takes/issues/833), can't put it on hold

**Comment by neonailol** [comment]
@yegor256 done https://github.com/jcabi/jcabi-parent/issues/78

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 @neonailol this PR was opened 8 days ago, I think it should be closed and resubmitted after jcabi/jcabi-parent#78 fix and jcabi-parent release.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#833](https://github.com/yegor256/takes/issues/833), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@neonailol ping

**Comment by paulodamaso** [comment]
@yegor256 please take a look, it's assigned to you. Please approve or reject it.

**Comment by yegor256** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@neonailol please fix or close this PR

**Comment by paulodamaso** [comment]
@yegor256 the build has failures, let's see if @neonailol fixes them before we try to merge again

**Comment by 0crat** [comment]
Job [#833](https://github.com/yegor256/takes/issues/833) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Code review was too long (212 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#833](https://github.com/yegor256/takes/issues/833) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request closed without merging**
