### PR TITLE
Building Takes with Gradle - How to contribute

### PR DESCRIPTION
**Pull request by marceloamadeu**
Including instructions for building and testing Takes with Gradle.

### CODE REVIEW

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@marceloamadeu Looks like the line does not work:
```
$ gradle clean build --refresh-dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clean' not found in root project 'takes'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace optionto get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by marceloamadeu** [comment]
@paulodamaso,  as it is the project, all developed using maven, it is not possible to convert and use gradle.
I suggest closing the job / ticket and i am available if you need more information.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#897` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
