### PR TITLE
Adding more test cases

### PR DESCRIPTION
**Pull request by sebing**
Fixing issue(https://github.com/yegor256/takes/issues/458)
Added testing multiple http methods.
This is a re creation of the PR(https://github.com/yegor256/takes/pull/551) As the merge did not happen to master

### CODE REVIEW

**Comment by davvd** [comment]
@sebing Thanks for your pull request, let me find someone who can review it

**Comment by sebing** [comment]
@davvd You did not find someone to review it?

**Comment by sebing** [comment]
@davvd anyone reviewing the PR?

**Comment by davvd** [comment]
@hdouss review this one,please

**Comment by HDouss** [comment]
@sebing The test you added checks if TkProxy accepts and forwards requests for different methods. I expected the test to check if TkProxy actually send the same method request as received., i.e : if it receives a PUT request, it forwards a PUT request. This is the sens of the puzzle.

**Comment by HDouss** [comment]
@sebing What about this part of the puzzle:
>the different combinations of request/response headers.

If you think the issue is big, create another puzzle.

**Comment by sebing** [comment]
@HDouss I am adding a new puzzle for testing different combinations of requests.

**Comment by sebing** [comment]
@HDouss Can you explain what you mean by testing the http forwards? What my understanding was the test is existing for checking the http PUT, extend the testing with other methods. 
Should I add another puzzle for checking the forwarding?

**Comment by HDouss** [comment]
@sebing My understanding was to test if TkProxy make a POST request if it receives a POST request, and make a DELETE request if it receives a DELETE request...

**Comment by sebing** [comment]
@HDouss Still I have not understood the problem. 
My understanding is this way
- The client send the data though an HTTP method (let say POST)
- The server returns the data. The Response doesn't include the HTTP method information (in my understanding)

If my understanding is right, what we have to check in the client testing?

**Comment by HDouss** [comment]
@sebing Talking about behaviors, not implementation details: we should test TkProxy behaviors which is (as its name suggest) act as a proxy to request another URL. That is, it should request that another URL the same way as the request TkProxy receive.
For test implementation detail, you should have something like this (pseudo-code):
```java
new FtRemote(
    new TkFork(
        new FkMethods("GET", new TkFixed("hello, get request!")),
        new FkMethods("POST", new TkFixed("hello, post request!")),
        new FkMethods("DELETE", new TkFixed("hello, delete request!")),
        ....
    )
).exec(...)
```
Then, you should assert that `new TkProxy(home).act(new RqFake(SOME_METHOD))` returns the expected response "hello, ???? request!"

**Comment by sebing** [comment]
@HDouss Thank you for your direction. 
I have added the testw to check if TkProxy actually send the same method request as received. Can you re-review them?

**Comment by HDouss** [comment]
@sebing Not exactly same scenario, but it tests at least that TkProxy is requesting with same method. Thanks.

**Comment by HDouss** [comment]
@rultor merge.

**Comment by yegor256** [comment]
@HDouss I think that "parametrized tests" will be more suitable here: https://github.com/junit-team/junit/wiki/Parameterized-tests

**Comment by sebing** [comment]
@HDouss I have parametrized the tests. Can you re-review the changes?

**Comment by HDouss** [comment]
@sebing Nice !

**Comment by HDouss** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@HDouss 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

Only two issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by HDouss** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@HDouss Thanks.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@hdouss I added 10 mins to @ypshenychka (for QA review) in transaction 81207668; Thanks for your contribution, **15 mins** was added to your account, payment ID is `81207695`, 145 hours and 11 mins spent total; added +15 to your rating, now it is equal to [+4313](http://www.netbout.com/b/36032?open=rating)

**Comment by HDouss** [comment]
@davvd According to the [policy](http://at.teamed.io/policy.html#8), a code review task have a bonus of "as many minutes as the number of comments". Please add my bonus accordingly.

**Comment by davvd** [comment]
> @davvd According to the [policy](http://at.teamed.io/policy.html#8), a code review task have a bonus of "as many minutes as the number of comments". Please add my bonus accordingly.

@hdouss @yegor256 could you please help us here?

**Pull request merged**
