### PR TITLE
#517 - Enabled FindBugs check in Qulice

### PR DESCRIPTION
**Pull request by alexey-krylov**
Resolving #517. Now FindBugs check in Qulice is enabled:

```
[INFO] [INFO] Starting FindBugs validator
[INFO] [INFO] JSR-303 validator org.hibernate.validator.internal.engine.ValidatorImpl instantiated by jcabi-aspects 0.22
/7e07127
[INFO] [INFO] jcabi-aspects 0.22/7e07127 started new daemon thread jcabi-loggable for watching of @Loggable annotated me
thods
[INFO] [INFO] Finishing FindBugs validator
```

### CODE REVIEW

**Comment by davvd** [comment]
@alexey-krylov Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by alexey-krylov** [comment]
@yegor256 please see my last comments related to issue #517

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by paulodamaso** [comment]
@alexey-krylov please resolve conflicts

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#531` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
