### PR TITLE
#485 Introduce AbstractHmBody matcher and implementations

### PR DESCRIPTION
**Pull request by t-izbassar**
PR for #485

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#785](https://github.com/yegor256/takes/issues/785) is now in scope, role is `REV`

**Comment by t-izbassar** [comment]
I've checked coverage lines. Jacoco qualify constructors in `HmRqBody` and in `HmRsBody` as not covered, that's why those classes are covered only for 33%. However, in `AbstractHmBody` coverage rate is 100% (for constructors) and as we only delegating construction to parent class I think that's enough. I don't want to write useless tests to cover all possible constructors. 

Also there is `describeTo` which is not covered intentionally as implementation is not full. If you think that I should write test anyway I can do it.

**Comment by t-izbassar** [comment]
I was able to fix coverage report. Looks OK now. @yegor256 don't you mind finding someone to review this PR? Thanks.

**Comment by 0crat** [comment]
This pull request [#785](https://github.com/yegor256/takes/issues/785) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@t-izbassar I'm not sure that this PR resolves bug-reporter issue fully, as I understand he wanted to provide hamcrest matchers as constructor parameters (not string or byte-array values), like:
```java
MatcherAssert.assertThat(
  response,
  new HmRsBody<>(Matchers.startsWith("<html"))
);
```
@carlosmiranda could you please take a look?

**Comment by t-izbassar** [comment]
@g4s8 I understand that. However body returns an `inputStream` from what we can read at most bytes. And at most we can only check that they are equal or maybe they starts with same sequence of bytes. I’m not sure that containing exact sequence of bytes is useful. That’s why I left the puzzle to distinguish bytes only bodies with texts. Your example will work only for text bodies.

**Comment by t-izbassar** [comment]
@g4s8 and how you think your example should work? I will read bytes from inputStream then I need to transform that bytes to a string and only then I can apply given matcher. That’s seems to me will lead to a wrong design with having to check if matcher is for certain type. However I can think of something if @carlosmiranda will suggests other possibilities.

**Comment by t-izbassar** [comment]
Hey @g4s8 what do you think? This puzzle with splitting for two different types of Bodies should be enough, so that we will have `HmTextBody` and `HmBytesBody` and we can safely apply matcher from your example to `HmTextBody` as it is body with string content. I think having them separate is better way than having to convert bytes to string if we have string matcher.

Or how we can convert string matcher to bytes matches? I think this will add complexity to the solution.

**Comment by g4s8** [comment]
@t-izbassar yes, I think it would be better. You can update a `@todo` (`@todo #485:30min Right now we can only check that InputStream`) with your [suggestion](https://github.com/yegor256/takes/pull/785#issuecomment-363483662) and I'll accept this PR.

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3790](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9495](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#785](https://github.com/yegor256/takes/issues/785) is now out of scope

**Pull request merged**
