### PR TITLE
#788 refactored TkFallback

### PR DESCRIPTION
**Pull request by krzyk**
#788 
* refactored TkFallback to reduce duplication

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#908](https://github.com/yegor256/takes/issues/908) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@krzyk thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#908` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#908](https://github.com/yegor256/takes/issues/908) is now out of scope

**Comment by simonjenga** [comment]
@krzyk OK :+1:

**Pull request merged**
