### PR TITLE
383 : PsGoogle creates incorrect UserInfo link

### PR DESCRIPTION
**Pull request by tiaped**
PR #383 is ready for review

### CODE REVIEW

**Comment by davvd** [comment]
@tiaped Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@tiaped what about a unit test?

**Comment by yegor256** [comment]
@tiaped are you planning to finish this PR?

**Comment by yegor256** [comment]
@tiaped I'm closing

**Comment by davvd** [comment]
@yegor256 thank you, added **18 mins** to your acc, payment num is `000-9cfebfde`, 623 hours and 38 mins spent in total to complete. you're getting extra minutes here (c=3). +18 added to your rating, at the moment it is: [+10691](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
