### PR TITLE
#669 Correct extraction of error message

### PR DESCRIPTION
**Pull request by xupyprmv**
#669 error message from google+ api 
I modified path to extract error message. I also updated test file.

### CODE REVIEW

**Comment by xupyprmv** [comment]
@davvd Please find someone to review.

**Comment by davvd** [comment]
@xupyprmv Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 Thanks for your contribution, **16 mins** was added to your account, payment ID is `000-1c4f417a`, 30 hours and 54 mins spent total; you're getting extra minutes here (c=1); +16 added to your rating, at the moment it is: [+1103](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
