### PR TITLE
For #943, created jacoco profile.

### PR DESCRIPTION
**Pull request by oridan**
For #943, created jacoco profile.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#967](https://github.com/yegor256/takes/issues/967) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#967](https://github.com/yegor256/takes/issues/967) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ad59b4d3-9fc7-47a4-95f0-9fbc9fe3176b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by oridan** [comment]
@fabriciofx ping

**Comment by oridan** [comment]
ping @fabriciofx

**Comment by oridan** [comment]
@paulodamaso could you review this PR?

**Comment by paulodamaso** [comment]
@oridan Let's give some more time do @fabriciofx

**Comment by paulodamaso** [comment]
@fabriciofx Please review this commit

**Comment by paulodamaso** [comment]
@oridan The PR looks good but I think that we won't execute the jacoco profile in CI that way. Please fix the configuration files for CI providers adding the profile `jacoco` to be executed too.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#967](https://github.com/yegor256/takes/issues/967), see [§21](http://www.zerocracy.com/policy.html#21); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by oridan** [comment]
@paulodamaso It is already configured in .travis.yml (https://github.com/yegor256/takes/blob/458b51f753d5e82398f1e4081850ca28dae17dd0/.travis.yml#L12)

**Comment by paulodamaso** [comment]
@oridan Thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#967](https://github.com/yegor256/takes/issues/967) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#967](https://github.com/yegor256/takes/issues/967) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
