### PR TITLE
(#1012) Replacing Utf8String with Cactoos primitives

### PR DESCRIPTION
**Pull request by fanifieiev**
This PR is for #1012

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1038](https://github.com/yegor256/takes/issues/1038) is assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/60b6f383-6e6f-4ebe-81b6-279e931d3515); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by paulodamaso** [comment]
@fanifieiev Seems good, thank you

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/1038#issuecomment-599164783))

@paulodamaso This pull request [#1038](https://github.com/yegor256/takes/issues/1038) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2075ac8c-11c2-478e-8760-16fc9d7b93d7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor merge

**Pull request merged**
