### PR TITLE
#842 migrated to velocity 2.0

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #842 I've migrated to velocity 2.0. For more details check #842.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#891](https://github.com/yegor256/takes/issues/891) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#891` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#891](https://github.com/yegor256/takes/issues/891) is now out of scope

**Comment by paulodamaso** [comment]
@rultor release, tag is `1.12`

**Pull request merged**
