### PR TITLE
Failing integration tests don't make the build to fail #436

### PR DESCRIPTION
**Pull request by HDouss**
Resolving #436.
Maven failsafe plugin is intended to let the build "succeed" during `integration-test` phase. It is during the `verify` phase that the check of the integration test result occurs and the build succeed or fail accordingly.
In order for the build (`verify` phase) to succeed, I made modifications on the `file-manager` project to make it qulice compliant.

### CODE REVIEW

**Comment by davvd** [comment]
@hdouss Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@pinaf please review, thanks

**Comment by pinaf** [comment]
@bdragan could you please make sure this works for you?

**Comment by pinaf** [comment]
@rultor merge

**Comment by HDouss** [comment]
@yegor256 Please confirm the merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by pinaf** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@pinaf added 10 mins to @ypshenychka, for QA review, payment code is `73954044`... I added **18 mins** to your account, many thanks for working with the project (AP-6FE14316SX524683L)! The completion time here was 74 hours and 18 mins.... extra minutes for review comments (c=3)... +18 added to your rating, at the moment it is: [+5256](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
