### PR TITLE
#37 added unit test for RqAuth

### PR DESCRIPTION
**Pull request by dmzaytsev**

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmzaytsev** [comment]
qulice checks has been passed before commit
I can't understand why Travis's build fails

**Comment by davvd** [comment]
@longtimeago review this one,please

**Comment by dmzaytsev** [comment]
just recreate the file... all check passed

**Comment by longtimeago** [comment]
@dmzaytsev yep, look good. Thanks!

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@longtimeago Much obliged! I have added **17 mins** to your account in payment "54285567", 14 hours and 8 mins spent; extra minutes for review comments (c=2); added +17 to your rating, now it is equal to [+3782](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
