### PR TITLE
For #784: Create Base interface for Request and Response.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #784: Create Base interface for Request and Response.
- Created interfaces `Head` and `Body`
- Wired them to `Request` and `Response`
- Corrected problems.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#845](https://github.com/yegor256/takes/issues/845) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#845](https://github.com/yegor256/takes/issues/845) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2471844566); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@paulodamaso I think we also need to notice in readme that version `2.0` is not backward compatible with previous vesions.

**Comment by paulodamaso** [comment]
@g4s8 I don't know where this kind of info would fit in readme; where do you suggest I'd put this?

**Comment by g4s8** [comment]
@paulodamaso I'd put it to the bottom of page before "How to contribute" but after "Optional dependencies"

**Comment by paulodamaso** [comment]
@g4s8 DOne, please take a look.

**Comment by g4s8** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@yegor256 please take a look at this

**Comment by paulodamaso** [comment]
@yegor256 ping, time is running out on this one

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (36 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#845](https://github.com/yegor256/takes/issues/845) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
> The code reviewer found at least three problems in the code 

Please, confirm that you will try to find at least three issues next time.

**Comment by g4s8** [comment]
@elenavolokhova sure, I confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by g4s8** [comment]
@0crat  status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/845#issuecomment-429289400))

@g4s8 This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#845](https://github.com/yegor256/takes/issues/845) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23845%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Pull request merged**
