### PR TITLE
Refactor HmRsHeader matcher to accept any header and value matchers

### PR DESCRIPTION
**Pull request by Happy-Neko**
Fix for #480. 

* Refactor `HmRsHeader` matcher to accept any header and value matchers.
* Make `IsEqualIgnoringCase` default header matcher when selecting headers by `String`.

### CODE REVIEW

**Comment by Happy-Neko** [comment]
@davvd Please proceed with code review.

**Comment by davvd** [comment]
@happy-neko Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@dmzaytsev review this one, please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by Happy-Neko** [comment]
@yegor256 Please confirm PR merge.

**Comment by yegor256** [comment]
@rultor merge

**Comment by Happy-Neko** [comment]
> @happy-neko @yegor256 Oops, I failed. You can see the full log here (spent 8min)

@yegor256 merge conflicts resolved.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@dmzaytsev 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by dmzaytsev** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@dmzaytsev Thank you

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @ypshenychka (for QA), payment ID is `74096888`... thanks, paid, **17 mins** to your account, payment ID is `74096902`, task took 294 hours and 41 mins to complete... you're getting extra minutes here (c=2)... +17 added to your rating, at the moment it is: [+1541](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
