### PR TITLE
#97 added decorator CcStrict

### PR DESCRIPTION
**Pull request by dmzaytsev**

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@ggajos please review, thanks

**Comment by ggajos** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by elenavolokhova** [comment]
@ggajos According to our [quality rules](http://www.teamed.io/qa.html): 
> The code reviewer found at least three problems in the code. 

There were no issues found during review. Please, try to find at least three problems next time.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here because no issues were found during code review.
>davvd commented 2 days ago
Many thanks for the PR, let me find a reviewer for it

And please, don't forget to address all your comments :)

**Comment by ggajos** [comment]
@elenavolokhova nobody found any issues here, is it a problem?

**Comment by elenavolokhova** [comment]
@ggajos The same question was answered [here](https://github.com/teamed/sigzig/pull/581). Could you please read last comments and contact @yegor256 if any questions left?

**Comment by ggajos** [comment]
@elenavolokhova thank you, clear

**Comment by elenavolokhova** [comment]
@ggajos not a problem :)

**Comment by yegor256** [comment]
@davvd I confirm, quality is acceptable here

**Comment by davvd** [comment]
> @davvd I confirm, quality is acceptable here

@yegor256 thanks for the review

**Comment by davvd** [comment]
@ggajos 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 54695029; Thank you, I have added **18 mins** to your account in payment/transaction "`AP-5HT07780LY587274J`", time consumed: 8 hours and 18 mins; you're getting extra minutes here (c=3); +18 added to your rating, at the moment it is: [+3349](http://www.netbout.com/b/35094?open=rating)

**Pull request merged**
