### PR TITLE
CcStrict should not touch urn() or anonymous identity

### PR DESCRIPTION
**Pull request by cyberone**
CcStrict should not touch urn() or anonymous identity. 

1. Wrapped CcStrict.appyrules with condition
1. Tested CcStrict.decode of anonymous identity

### CODE REVIEW

**Comment by davvd** [comment]
@cyberone Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@carlosmiranda review this one, please

**Comment by carlosmiranda** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by elenavolokhova** [comment]
@carlosmiranda 
According to our [quality rules](http://www.teamed.io/qa.html):
 > Pull request description explains the solution proposed and contains a link to the original ticket it is related to.
 
 There is no link to original ticket in description. Please, fix it.

According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review. We should get used to this rule as soon as possible.
Please confirm that you will try to find at least three problems next time.

**Comment by carlosmiranda** [comment]
@cyberone Please link to the original ticket in the description. @elenavolokhova We will find three or more issues next time.

**Comment by cyberone** [comment]
@carlosmiranda done

**Comment by carlosmiranda** [comment]
@cyberone Thanks!

**Comment by carlosmiranda** [comment]
@elenavolokhova All issues are addressed and everything is clear to us, we'll work better next time.

**Comment by elenavolokhova** [comment]
@carlosmiranda @cyberone Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@carlosmiranda 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 56387847. **19 mins** sent to your balance (ID `56387850`), many thanks! It took 47 hours and 35 mins.. you're getting extra minutes here (c=4). +19 added to your rating, at the moment it is: [+4565](http://www.netbout.com/b/35023?open=rating)

**Pull request merged**
