### PR TITLE
#723 Inclusion of Maven eclipse plugin in Build file

### PR DESCRIPTION
**Pull request by simonjenga**
It would be great to include Maven Eclipse plugin in the Build file as it simplifies working with the Eclipse IDE.
Although the plugin is no longer maintained, it is still useful: 

http://maven.apache.org/plugins/maven-eclipse-plugin/

### CODE REVIEW

**Comment by davvd** [comment]
@simonjenga Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@essobedo please review this pull request and keep [this article](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) in mind

the budget is 15 mins for this review

**Comment by essobedo** [comment]
@simonjenga please add in the description of your PR the id of the related ticket. Check [this](https://github.com/yegor256/takes/pull/717) for example.

**Comment by simonjenga** [comment]
@essobedo Unfortunately, this PR does not have an associated ticket that was submitted as an issue. It is only a minor issue although i can submit a ticket so that we can have an ID. Should i do so?

**Comment by simonjenga** [comment]
@essobedo Ok, I will do so and get back to you...

**Comment by simonjenga** [comment]
@essobedo I have crated the issue ticket #723 to this PR.

Let us wait and see what the Architect says about it...

**Comment by essobedo** [comment]
@simonjenga perfect thank you

**Comment by ruurd** [comment]
DO NOT MERGE THIS. What good does that plugin do for people that do not use Eclipse. If you want to use Eclipse, be my guest, but don't foist some Eclipse specific plugin onto users of different IDEs.

**Comment by essobedo** [comment]
@simonjenga the ticket has been rejected, please close your PR.

**Comment by simonjenga** [comment]
@essobedo Sure!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#722` was not in scope

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@simonjenga 
According to our [QA Rules](http://at.teamed.io/qa.html):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please add the link to original issue into the description of the PR.

**Comment by ypshenychka** [comment]
@ruurd 
>ruurd commented on 2 Mar
DO NOT MERGE THIS. What good does that plugin do for people that do not use Eclipse. If you want to use Eclipse, be my guest, but don't foist some Eclipse specific plugin onto users of different IDEs.

According to our [QA Rules](http://at.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your message by indicating an addressee in the beginning.

**Comment by simonjenga** [comment]
@ypshenychka I have now added the link to the original issue into the description of this PR; please check the description.

I had also added the link in the title of this PR ```#723 Inclusion of Maven eclipse plugin in Build file```

**Comment by ypshenychka** [comment]
@simonjenga Thank you!

**Comment by ypshenychka** [comment]
@ruurd Please consider my above [comment](https://github.com/yegor256/takes/pull/722#issuecomment-300834376) and make appropriate correction.

**Pull request closed without merging**
