### PR TITLE
#528 - updated years

### PR DESCRIPTION
**Pull request by fabriciofx**

### CODE REVIEW

**Comment by davvd** [comment]
@fabriciofx Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@dmzaytsev it's yours, please review

**Comment by dmzaytsev** [comment]
@fabriciofx Travis CI build failed
>/home/travis/build.sh: line 45: ./years.sh: Permission denied

let's fix it

**Comment by dmzaytsev** [comment]
@fabriciofx according the quality rules http://at.teamed.io/qa.html
>Pull request title explains the problem it is fixing.
Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

please update the pull request description

**Comment by dmzaytsev** [comment]
@fabriciofx  there are too many files in PR so I can't comment inside the diff

```
if (grep -L -r 2015-`date +%Y` --exclude-dir ".git" --exclude ".*" --exclude-dir "est" --exclude "*.yml" --exclude "*.md" --exclude-dir "target" . | egrep -v "(curl-appveyor.cfg.asc|src/it/file-manager/invoker.properties|src/it/file-manager/src/main/resources/org/takes/it/fm/about.html|src/main/resources/org/takes/version.properties|src/site/resources/CNAME|src/site/resources/logo|src/test/resources/org/takes/http/keystore|src/test/resources/org/takes/rs|src/www.takes.org/index.html|years.sh)"); then
    echo "Files above have wrong years in copyrights"
    exit 1
else
    exit 0;
fi
```

but take a look at the comment https://github.com/teamed/qulice/pull/624#discussion_r50050552

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This PR wasn't merged and review was not performed fully. I assume the quality is bad here.

**Comment by davvd** [comment]
> @davvd This PR wasn't merged and review was not performed fully. I assume the quality is bad here. 

@elenavolokhova OK, thanks, we'll try to be better next time

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `75633265`

**Pull request closed without merging**
