### PR TITLE
(#1016) Removed unnecessary class Utf8PrintStream

### PR DESCRIPTION
**Pull request by fanifieiev**
This PR is for #1016

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1042](https://github.com/yegor256/takes/issues/1042) is assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/244a69a4-d3ba-4758-81b9-573d75e00748); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/1042#issuecomment-607855544))

@paulodamaso The user @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898) resigned from [#1042](https://github.com/yegor256/takes/issues/1042), please stop working. Reason for job resignation: Order was cancelled

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/1042#issuecomment-614195733))

@paulodamaso This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1042](https://github.com/yegor256/takes/issues/1042) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @fanifieiev[/z](https://www.0crat.com/u/fanifieiev): This user reported the ticket
    * @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%231042%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/1042#issuecomment-618145201))

@paulodamaso Job [#1042](https://github.com/yegor256/takes/issues/1042) is closed, can't start order

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/1042#issuecomment-619480742))

@paulodamaso Job `gh:yegor256/takes#1042` is not assigned, can't get performer

**Pull request merged**
