### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tertioptus**
Added clickable "table of contents" under project summary.

### CODE REVIEW

**Comment by davvd** [comment]
@tertioptus Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@mkordas it's yours, please review

**Comment by mkordas** [comment]
@Tertioptus thanks for a PR. How did you create this ToC? Manually or by some generator?

**Comment by Tertioptus** [comment]
Manually.  Quasi-manually, I used vim.

**Comment by mkordas** [comment]
@Tertioptus all right, so I will check it. Is there any corresponding issue/task that you are fixing here or it's just random PR?

**Comment by Tertioptus** [comment]
just the Table of contents

**Comment by mkordas** [comment]
@Tertioptus OK, looks good

**Comment by mkordas** [comment]
@rultor merge

**Comment by mkordas** [comment]
@yegor256 please decide what to do here. Contents is fine, but cosmetic. There is no corresponding issue here though...

**Comment by mkordas** [comment]
@yegor256 we need your opinion here

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by ypshenychka** [comment]
@Tertioptus 
>Added clickable "table of contents" under project summary.

According to our [QA Rules](http://at.teamed.io/qa.html):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please add a link to initial issue into PR's description.

**Comment by ypshenychka** [comment]
@Tertioptus 
1. 
>Manually.  Quasi-manually, I used vim.

2.
>just the Table of contents

According to our [QA Rules](http://at.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your messages by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@mkordas 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by mkordas** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@mkordas Thanks.

**Comment by ypshenychka** [comment]
@Tertioptus Please consider my above remarks.

**Comment by ypshenychka** [comment]
@Tertioptus ping

**Pull request merged**
