### PR TITLE
Fix for #251 (RqWithHeaderTest tests nothing)

### PR DESCRIPTION
**Pull request by cyberone**
Fix for https://github.com/yegor256/takes/issues/251 RqWithHeaderTest tests nothing)

1. Replaced `Host` header with `X-Custom-header`

### CODE REVIEW

**Comment by davvd** [comment]
@cyberone Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@pinaf it's yours, please review

**Comment by pinaf** [comment]
@rultor merge
@cyberone looks good. thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by pinaf** [comment]
@yegor256 this was merged 15 days ago :(

**Comment by yegor256** [comment]
@pinaf it's marked as "invalid", see http://www.teamed.io/policy.html#13

**Comment by pinaf** [comment]
@yegor256 I see. Why was it assigned to me?

**Comment by yegor256** [comment]
@pinaf good question. it's our mistake. we'll try to avoid this in the future and will assign small pull requests directly to project architect, without a code reviewer.

**Comment by pinaf** [comment]
@yegor256 ok got it. thanks.

**Pull request merged**
