### PR TITLE
fix build & run link in README

### PR DESCRIPTION
**Pull request by djds23**
This link was not pointing to the correct anchor tag in the README. Now it correctly takes the user to the right section.

Thanks for the project!

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#772](https://github.com/yegor256/takes/issues/772) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#772](https://github.com/yegor256/takes/issues/772) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@yegor256 looks good, can be merged

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3400](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7805](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#772](https://github.com/yegor256/takes/issues/772) is now out of scope

**Pull request merged**
