### PR TITLE
#802 Nulls Removed - FkHitRefresh.java

### PR DESCRIPTION
**Pull request by marceloamadeu**
Continue to remove nulls as requested in PR #802

### CODE REVIEW

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#934` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
