### PR TITLE
(#1015) Removed unecessary class Sprintf

### PR DESCRIPTION
**Pull request by fanifieiev**
This PR is for #1015

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1044](https://github.com/yegor256/takes/issues/1044) is assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/0543a88f-fdb4-410d-895e-194856e4c622); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/1044#issuecomment-607856017))

@paulodamaso The user @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898) resigned from [#1044](https://github.com/yegor256/takes/issues/1044), please stop working. Reason for job resignation: Order was cancelled

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/1044#issuecomment-619480883))

@paulodamaso Job `gh:yegor256/takes#1044` is not assigned, can't get performer

**Pull request merged**
