### PR TITLE
#530 - updated qulice to 0.15.4

### PR DESCRIPTION
**Pull request by exper0**
#530 - updated qulice to 0.15.2, fixed checkstyle bugs, created puzzle to fix PMD and xml bugs

### CODE REVIEW

**Comment by exper0** [comment]
@davvd please find reviewer for this one

**Comment by davvd** [comment]
@exper0 Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@carlosmiranda this pull request is for you, please review

**Comment by carlosmiranda** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@exper0 There are some merge conflicts, please resync.

**Comment by exper0** [comment]
@carlosmiranda @yegor256 resolved merge  conflict, please try one more time

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by ypshenychka** [comment]
@carlosmiranda 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by ypshenychka** [comment]
@exper0 The titile states "updated qulice to 0.15.4" and description states "updated qulice to 0.15.2". Please correct description by providing actual version number for qulice.

**Comment by exper0** [comment]
@ypshenychka done(changed description to actual version 0.15.4)

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@exper0 @carlosmiranda Thank you!

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@carlosmiranda 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75970967. I added **19 mins** to your account, many thanks for working with the project (75970980)! The completion time here was 170 hours and 20 mins.. you're getting extra minutes here (c=4). +19 added to your rating, at the moment it is: [+2579](http://www.netbout.com/b/35023?open=rating)

**Pull request merged**
