### PR TITLE
#847 Add "How to contribute" session in README.md to Gradle users

### PR DESCRIPTION
**Pull request by fabriciofx**
@paulodamaso I've started to add Gradle support to Takes. However, Gradle there are some problems using it, like errors in tests (20) and need add support to use Qulice too. These new tasks will need add them like PDD puzzles, but I don't know how do it in documentation or gradle configuration file. What I should do?

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#919](https://github.com/yegor256/takes/issues/919) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@fabriciofx Thanks for the PR, but thinking better about this issue looks like we don't need another build / dependency management tool besides maven. Adding gradle support would make us to add all or CI tools to work with gradle too, duplicating them, and I don't think it is worth it.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#919` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#919](https://github.com/yegor256/takes/issues/919) is now out of scope

**Pull request closed without merging**
