### PR TITLE
#528 - updated years

### PR DESCRIPTION
**Pull request by fabriciofx**

### CODE REVIEW

**Comment by davvd** [comment]
@fabriciofx Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@dmzaytsev this pull request is for you,please review

**Comment by dmzaytsev** [comment]
@fabriciofx you have created 4 pull requests for the one ticket ... 
just push into the same branch instead of creation of PR

**Comment by fabriciofx** [comment]
@dmzaytsev I'm so sorry! I'm a newbie, but I learn fast! :) Thank you for this information!

**Comment by dmzaytsev** [comment]
@fabriciofx according the quality rules http://at.teamed.io/qa.html

>Pull request title explains the problem it is fixing.
Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

please update the pull request description

**Comment by dmzaytsev** [comment]
@fabriciofx this is your `years.sh`
```
#!/bin/sh

if (grep -L -r 2015-`date +%Y` --exclude-dir ".git" --exclude ".*" --exclude-dir "est" --exclude "*.yml" --exclude "*.md" --exclude-dir "target" . | egrep -v "(curl-appveyor.cfg.asc|src/it/file-manager/invoker.properties|src/it/file-manager/src/main/resources/org/takes/it/fm/about.html|src/main/resources/org/takes/version.properties|src/site/resources/CNAME|src/site/resources/logo|src/test/resources/org/takes/http/keystore|src/test/resources/org/takes/rs|src/www.takes.org/index.html|years.sh)"); then
    echo "Files above have wrong years in copyrights"
    exit 1
else
    exit 0;
fi
```

take a look at the comment teamed/qulice#624 (comment)

**Comment by dmzaytsev** [comment]
@fabriciofx btw you not assigned to #528

**Comment by dmzaytsev** [comment]
@fabriciofx furthermore #523 not accepted by @yegor256 yet
I would suggest stop working on this issue for now

**Comment by dmzaytsev** [comment]
@yegor256 what will we do with this PR ?
 #523 still not registered as a bug and @fabriciofx not assigned to the ticket

**Comment by yegor256** [comment]
@dmzaytsev I would suggest to drop it

**Comment by dmzaytsev** [comment]
@fabriciofx please close this pull request

**Comment by dmzaytsev** [comment]
@yegor256 can we close this PR?

**Pull request closed without merging**
