### PR TITLE
#780 Implement Condition.Range

### PR DESCRIPTION
**Pull request by t-izbassar**
PR for #780

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#801](https://github.com/yegor256/takes/issues/801) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#801](https://github.com/yegor256/takes/issues/801) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/460913167). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@t-izbassar method `fits()` has a side-effect, it's not clear and may produce unpredictable behavior, because each call to this method will change internal state of an object.
Also I don't think that it's a correct design to implement `Range` as a `Condition` type (because range is not a condition logically) and use it inside `Select`:
```java
new Select<Integer>(
  Arrays.asList(3, 5, 7, 9, 11, 13, 15),
  new Condition.Range<Integer>(2, 4)
); // -> [7, 9, 11]
```
In my opinion `Range` should be `Iterable` and used like this:
```java
new Range<Integer>(
  Arrays.asList(3, 5, 7, 9, 11, 13, 15),
  2,
  4
); // -> [7, 9, 11]
```
@yegor256 what do you think? Maybe we can use https://github.com/yegor256/cactoos here?

**Comment by t-izbassar** [comment]
@g4s8 I agree about side-effect, but that's the only possible way to do this task. `Range` can be a condition because the condition is that the `element` fits given range. I don't see semantic misconception in that case. Also, this is what was requested by original issue:  #281.

Your suggestion is valid. However, it cannot be used with `Select` and cannot be combined with other conditions. Example:

```
new Select<Integer>(
  Arrays.asList(3, 5, 7, 9, 11, 13, 15),
  new Condition.Not<Integer>(
    new Condition.Range<Integer>(
      2, 
      4
    )
  )
)
```

**Comment by t-izbassar** [comment]
@g4s8 and can you clarify, what exactly an unpredictable behavior is? When `Range` object is created, it's leave with the state, and state changes. That's seems natural to an object. It's still immutable. Also, the usage of conditions are limited to `Select`, which checks the boundaries within `Iterable`.

Of course, if very same object will be used in two different selects, behavior will be questionable. However, what is your take on this issue? I don't see how I can possibly address that. Maybe, just mentioning in javadoc of the class will be useful?

**Comment by g4s8** [comment]
@t-izbassar 
> can you clarify, what exactly an unpredictable behavior is?

I mean that `Range.fits` expected to be used only in `Select` because `Select` knows that each call to `fits()` will change internal counter. If `Range` is used in other classes, it will cause some maintenance issues, because each class which use `Range` must know how it implemented internally.

> requested by original issue: #281.

This `Range` implementation was mentioned in a comment https://github.com/yegor256/takes/issues/281#issuecomment-101216901 (not in a task description), this is why I'm aksing @yegor256  to look at this changes. If this comment is fully valid, I'd accept this PR.

**Comment by t-izbassar** [comment]
@g4s8 original task requested to have `Condition.Skip`. And skip is easy operation when you have `Range`. So this could be treated as being relevant part to what was requested originally. Also implementing `Skip` without `Range` will be harder. And it will have all the issues that you've already mentioned. It will have side-effect.

The whole purpose of having `Condition` is to use it in `Select`. The all test cases even placed in `SelectTest`. So I would not reject that as being coupled to `Select` usage - that's just design decision. If you think it is wrong, then you can submit issue or propose something else. But, with regards to implemented design, I believe this solution is valid.

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 looks like we are reinventing what Cactoos already has, you are right... Maybe we should just let Takes have one dependency on Cactoos?

**Comment by t-izbassar** [comment]
@yegor256 @g4s8 I can add this dependency in this PR and left puzzles to delete this `Select` and `Condition` staff. Will it be okay?

**Comment by g4s8** [comment]
@t-izbassar I think you can keep this code, just add a `@todo` to replace `Select` and `Condition` with Cactoos analogs

**Comment by t-izbassar** [comment]
@g4s8 done

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by t-izbassar** [comment]
@yegor256 can you merge this one?

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@yegor256 hi, can you re-trigger this merge as well? Thanks.

**Comment by t-izbassar** [comment]
@yegor256 ping for the merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by t-izbassar** [comment]
@elenavolokhova confirmed.
> @t-izbassar Please, add some explanation of the solution proposed to the description section.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@elenavolokhova sure, I confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/takes/issues/801#issuecomment-368200961))

@elenavolokhova There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '//*[@id='45.share']/text()' not found in '<?xml version="1.0" encoding="UTF-8"?><html xmlns=..35780..</script>\uA      </body>\uA   \uA</html>': Index (0) is out of bounds (size=0)
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+83](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4615](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/takes/issues/801#issuecomment-368200961))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10824](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
This pull request [#801](https://github.com/yegor256/takes/issues/801) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/572017997). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/801#issuecomment-370139589))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#801](https://github.com/yegor256/takes/issues/801) is [in scope](http://www.zerocracy.com/policy.html#14) for 16days
  * The role is `REV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23801%27%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 could you please remove this job from WBS?

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/801#issuecomment-370910369). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#801](https://github.com/yegor256/takes/issues/801), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/801#issuecomment-371965018))

@yegor256 The job [#801](https://github.com/yegor256/takes/issues/801) is now out of scope

**Pull request merged**
