### PR TITLE
implements persistent connection

### PR DESCRIPTION
**Pull request by hs3180**
the persistent connection feature implementation refered in #306 
unit test in #393

### CODE REVIEW

**Comment by davvd** [comment]
@hs3180 Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@pinaf please review, thanks

**Comment by hs3180** [comment]
@davvd @pinaf
This PR is based on #393 . 
Please wait for #393.

**Comment by pinaf** [comment]
@hs3180 please let me know when I can start the CR.

**Comment by pinaf** [comment]
@hs3180 ping

**Comment by pinaf** [comment]
@hs3180 hello?

**Comment by hs3180** [comment]
@pinaf 
I'm sorry. @davvd ask me to stop working with this issue #306.

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is bad here as far as reviewer didn't have a chance to review this PR before it was closed without merge.

**Comment by davvd** [comment]
> @davvd Quality is bad here as far as reviewer didn't have a chance to review this PR before it was closed without merge. 

@elenavolokhova thank you very much

**Comment by davvd** [comment]
@pinaf 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 66961250

**Pull request closed without merging**
