### PR TITLE
Response pipe broke

### PR DESCRIPTION
**Pull request by t-izbassar**
Implementation for #373 . I decided to wrap `Back` in `FtBasic` in `BkSafe` so that default usage of `FtBasic` will be safe.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#776](https://github.com/yegor256/takes/issues/776) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#776](https://github.com/yegor256/takes/issues/776) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3685](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#776](https://github.com/yegor256/takes/issues/776) is now out of scope

**Pull request merged**
