### PR TITLE
Rename classes to make them more idiomatic #904

### PR DESCRIPTION
**Pull request by Serranya**
As discussed with @Iprogrammerr in #904 I renamed some classes to make them more idiomatic.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#972](https://github.com/yegor256/takes/issues/972) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#972](https://github.com/yegor256/takes/issues/972) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/d84f803e-aaa0-4c78-9bdf-c3b2cca1dd01); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@fabriciofx ping

**Comment by Serranya** [comment]
@paulodamaso the Reviewer is not reviewing this PR. Can you review this or assign a different reviewer?

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#972](https://github.com/yegor256/takes/issues/972) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't inspect

**Comment by 0crat** [comment]
Code review was too long (41 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#972](https://github.com/yegor256/takes/issues/972) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@paulodamaso there is nothing to comment when viewing PR about renaming classes, however, if it was not that simple task, you would need find at least 3 problems in code, as mentioned in [policy](http://www.zerocracy.com/policy.html#30)

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +20 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by paulodamaso** [comment]
@sereshqua Some comments about your QA review:
- The issue was not resolved by the performer: @fabriciofx should make the review, but I ended doing it (and merging after that), so the quality should me marked as `bad` for the performer (@fabriciofx )
- I suppose that in https://github.com/yegor256/takes/pull/972#issuecomment-484099222 you are warning me about my review, that I weren't able to find any issues and should try to find them in next reviews. This is unnecessary because I'm the architect of the project and I'm not assigned to this review task in particular. Annjyways, if this was your intent, you should wait a few days for my confirmation before giving your veredict
- In the end the quality veredict should be bad anyway: the reviewed did not performed the task

Don't worry about the result of this issue, though: as the project is without budget, no funds were spent. Just remember these tips when reviewing issues that were closed by the architect without the reviewer action, and keep up the good work

**Comment by sereshqua** [comment]
@paulodamaso thank for detailed explanation! agreed and understood!

**Pull request merged**
