### PR TITLE
Issue 1303 solved.

### PR DESCRIPTION
**Pull request by UFA-MOROZOV**
@yegor256, please review

### CODE REVIEW

**Comment by yegor256** [comment]
@UFA-MOROZOV how do know it's solved? Maybe you can create a unit test that reproduces the problem first?

**Comment by UFA-MOROZOV** [comment]
> @UFA-MOROZOV how do know it's solved? Maybe you can create a unit test that reproduces the problem first?

I used this test, before code refactoring from me it throwed exception, after it everything is ok:

@Test
    void readsWithLenGreaterThanTotalSize() throws IOException {
        final String data = "Hello, World!";
        final String length = Integer.toHexString(data.length());
        final InputStream stream = new ChunkedInputStream(
                IOUtils.toInputStream(
                        new Joined(
                                ChunkedInputStreamTest.CRLF,
                                length,
                                data,
                                ChunkedInputStreamTest.END_OF_CHUNK,
                                ""
                        ).toString(),
                        StandardCharsets.UTF_8
                )
        );
        final byte[] buf = new byte[data.length() + 10];
        final int bytesRead = stream.read(buf);
        MatcherAssert.assertThat(bytesRead, Matchers.equalTo(data.length()));
        MatcherAssert.assertThat(buf, Matchers.equalTo((data + new String(new byte[10])).getBytes()));
        MatcherAssert.assertThat(stream.available(), Matchers.equalTo(0));
        stream.close();
    }

**Comment by UFA-MOROZOV** [comment]
@yegor256, i can add this test to corresponding file in repository, but i don't think it's necessary, since it not so common issue in most cases.

**Comment by yegor256** [comment]
@UFA-MOROZOV we usually don't make changes without tests that confirm that the changes are needed

**Comment by UFA-MOROZOV** [comment]
error
@yegor256, i commited updated ChunkedInputStreamTest and run it with and without changes in ChunkedInputStream. Result without changes creates an error, where "Hello, world!" is considered as 12 symbols because of said Issue. I attached screenshots of test without changing ChunkedInputStream.

**Comment by yegor256** [comment]
@UFA-MOROZOV now it looks very good. However, the formatting of the code is a bit off. See what `qulice` is saying. Run the build locally: `mvn clean install -Pqulice`

**Comment by UFA-MOROZOV** [comment]
@yegor256 i refactored code and ran qulice, now it is alright.

**Comment by yegor256** [comment]
@UFA-MOROZOV thanks!

**Pull request merged**
