### PR TITLE
#268 RsWithHeaders puzzle resolution

### PR DESCRIPTION
**Pull request by ekondrashev**
Please review this PR for #268 issue. 
It actually removes the puzzle as for the #275 defect resolution.

### CODE REVIEW

**Comment by davvd** [comment]
@ekondrashev Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@carlosmiranda it's yours, please review

**Comment by carlosmiranda** [comment]
@rultor let's merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
