### PR TITLE
Typo in author's email address

### PR DESCRIPTION
**Pull request by szpecku**
There were 3 typos in email address of Dmitry Zaytsev.

### CODE REVIEW

**Comment by davvd** [comment]
@szpecku Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@szpecku thanks!

**Comment by davvd** [comment]
@yegor256 **16 mins** sent to your balance (ID `000-10dcaf80`), many thanks! It took 19 hours and 56 mins.... review comments (c=1) added as a bonus... +16 to your rating, your total score is [+4531](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
