### PR TITLE
#441: Added close of inputStream in org.takes.rs.RsXSLT.consume(Input…

### PR DESCRIPTION
**Pull request by gauee**
Closing inputStream in org.takes.rs.RsXSLT.consume(InputStream) #441

### CODE REVIEW

**Comment by davvd** [comment]
@gauee Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 Thank you, I have added **16 mins** to your account in payment/transaction "`000-84525c21`", time consumed: 15 hours and 15 mins. extra minutes for review comments (c=1). +16 added to your rating, at the moment it is: [+8409](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
