### PR TITLE
 Estimation of the project size 

### PR DESCRIPTION
**Pull request by ikhvostenkov**
This is fix for https://github.com/yegor256/takes/issues/149.

### CODE REVIEW

**Comment by ikhvostenkov** [comment]
@davvd PR is ready for review.

**Comment by davvd** [comment]
@ikhvostenkov Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@pinaf this pull request is for you, please review

**Comment by davvd** [comment]
> @davvd PR is ready for review.

@ikhvostenkov thank you, I will check it

**Comment by ikhvostenkov** [comment]
@davvd original ticket has been closed so far. Shall we merge this PR or?

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@ikhvostenkov 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide appropriate description about what was done in scope of PR.

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. Try to find at least three problems while future reviews.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by pinaf** [comment]
@ypshenychka Yes it's clear. Usually there are no issues found when reviewing these estimates :(

**Comment by ypshenychka** [comment]
@pinaf Thank you, I see. But as per [comment in PR #764](https://github.com/teamed/sigzig/pull/764#issuecomment-99655338), we should try to find some issues in this kind of PRd as well.

**Comment by ikhvostenkov** [comment]
@ypshenychka fixed description.

**Comment by ypshenychka** [comment]
@ikhvostenkov Great! Thank you.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@pinaf I added 10 mins to @ypshenychka (for QA review) in transaction 59135526... **17 mins** added to your account (payment number `AP-39G09874EG069254X`), many thanks for your contribution! 54 hours and 27 mins spent here.... review comments (c=2) added as a bonus... +17 to your rating, your total score is [+6961](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
