### PR TITLE
fix https://github.com/yegor256/takes/issues/945

### PR DESCRIPTION
**Pull request by Kartofanych**
move RqHrefSmart and RqHrefBase out of interface

### CODE REVIEW

**Comment by Kartofanych** [comment]
@yegor256 check please

**Comment by yegor256** [comment]
@Kartofanych what is the motivation for this? We have certain design style already, where supplementary classes stay inside interfaces. Why changing this for these particular ones?

**Comment by Kartofanych** [comment]
> @Kartofanych what is the motivation for this? We have certain design style already, where supplementary classes stay inside interfaces. Why changing this for these particular ones?

this is fix of issue https://github.com/yegor256/takes/issues/945
you asked to check issues that repository has - i found this one

**Comment by Kartofanych** [comment]
@yegor256 Any updates on this? (course is already finished)

**Comment by yegor256** [comment]
@Kartofanych the issue #945 was just a proposal, not an accepted bug (I closed it now). Please, look at the issues that are labeled as "bug" only

**Pull request closed without merging**
