### PR TITLE
#49 added unit test for TkMeasured 

### PR DESCRIPTION
**Pull request by d-molotchko**

### CODE REVIEW

**Comment by davvd** [comment]
I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@pinaf this pull request is for you,please review

**Comment by pinaf** [comment]
@d-molotchko please separate this into 2 PR's, one for each issue. Keep one on this PR and create a new one. Also, make sure you inform the person who created the issue of the PR number by making a reference.

**Comment by pinaf** [comment]
@d-molotchko when you pick which issue this PR is for, push it again to your branch and I'll take a look. Thanks!

**Comment by d-molotchko** [comment]
@pinaf I redid the repository so this PR was closed. Sorry.
I pushed another PRs, one per issue.

**Comment by pinaf** [comment]
@davvd @yegor256 I guess I need to be reassigned to one of the new PRs, correct?

**Comment by yegor256** [comment]
@pinaf not necessarily you, someone will help there. your job here is done, thanks.

**Comment by pinaf** [comment]
@yegor256 cool thanks.

**Comment by davvd** [comment]
@pinaf Many thanks! **17 mins** were added to your account in Transaction ID `AP-2B913239ER6810915`... you're getting extra minutes here (c=2)... +17 to your rating, your total score is [+4782](http://www.netbout.com/b/35128?open=rating)

**Pull request closed without merging**
