### PR TITLE
(#958) Upgrades jcabi-parent to v0.49.5

### PR DESCRIPTION
**Pull request by baudoliver7**
For #958 :

- Change jcabi-parent from `0.49.1` to `0.49.5` to solve xcop issue on windows
- Remove Hibernate validator dependency in pom.xml file

### CODE REVIEW

**Comment by 0crat** [comment]
@baudoliver7[/z](https://www.0crat.com/u/baudoliver7) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by baudoliver7** [comment]
@yegor256 Ok, let me take a look please.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1097` is not assigned, can't get performer

**Comment by baudoliver7** [comment]
@yegor256 Please, check/merge

**Comment by baudoliver7** [comment]
@yegor256 ready to be merge

**Comment by baudoliver7** [comment]
@yegor256 please, check/merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@baudoliver7 thanks!

**Pull request merged**
