### PR TITLE
#341 fixed google path

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #341 

* fixed incorrect google url
* added unit test

### CODE REVIEW

**Comment by davvd** [comment]
@dmzaytsev I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 I just added **16 mins** to your account, many thanks for your contribution (000-cb245908).. 1 hour and 24 mins spent here... you're getting extra minutes here (c=1)... added +16 to your rating, now it is equal to [+13054](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
