### PR TITLE
For #786: Correct HmRqHeader and HmRsHeader constructors

### PR DESCRIPTION
**Pull request by paulodamaso**
For #786:
- Removed constructors from `AbstractHmHeader`
- Added constructors to `HmRqHeader` and `HmRsHeader`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#843](https://github.com/yegor256/takes/issues/843) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#843](https://github.com/yegor256/takes/issues/843) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2440249053); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 accepted

**Comment by paulodamaso** [comment]
@yegor256 please take a look, there is something wrong in the project configuration: `[WARNING] The requested profile "jacoco" could not be activated because it does not exist.`

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@g4s8 please take a look at this review, we're running out of time

**Comment by g4s8** [comment]
@paulodamaso I see, but I've already accepted this PR, only @yegor256 can merge it.

**Comment by paulodamaso** [comment]
@g4s8 sorry, I didn't understood your acceptance in https://github.com/yegor256/takes/pull/843#issuecomment-417841687.

**Comment by paulodamaso** [comment]
@yegor256 please take a look at this review, we're running out of time here

**Comment by paulodamaso** [comment]
@yegor256 looks like it's already good to merge, please take a look

**Comment by paulodamaso** [comment]
@yegor256 ping, @g4s8 will lose the revision soon

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (39 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#843](https://github.com/yegor256/takes/issues/843) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
> The code reviewer found at least three problems in the code 

Please, confirm that you will try to find at least three issues next time.

**Comment by g4s8** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@g4s8 Thank you.

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
