### PR TITLE
For #1077: Update Qulice to 0.18.19 

### PR DESCRIPTION
**Pull request by andreoss**
Per #1077 

- Update Qulice
- Fix complains

### CODE REVIEW

**Comment by paulodamaso** [comment]
@0crat let's wait for #1067

**Comment by 0crat** [comment]
> @0crat let's wait for #1067  ([here](https://github.com/yegor256/takes/issues/1086#issuecomment-719948416))

@paulodamaso Can't understand "let's", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by andreoss** [comment]
@paulodamaso #1067 is done. Please take a look

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by yegor256** [comment]
@paulodamaso just try again, it's a temporary problem

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by andreoss** [comment]
@paulodamaso Let's try again.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1086` is not assigned, can't get performer

**Pull request merged**
