### PR TITLE
Added unit test for TkMeasured

### PR DESCRIPTION
**Pull request by d-molotchko**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@ggajos please review, thanks

**Comment by d-molotchko** [comment]
I close this pull request because coding style

**Comment by yegor256** [comment]
@d-molotchko no need to close pull request, just commit your changes to the same branch and Github will pick them up

**Comment by davvd** [comment]
@ggajos I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by d-molotchko** [comment]
@davvd I close this PR

**Pull request closed without merging**
