### PR TITLE
deps: bump cactoos, cactoos-matchers and jcabi-parent

### PR DESCRIPTION
**Pull request by baudoliver7**
Close: #1069

### CODE REVIEW

**Comment by baudoliver7** [comment]
@yegor256 please, check/merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@baudoliver7 thanks!

**Comment by baudoliver7** [comment]
@yegor256 Hi, could you release a new version please ?

**Comment by yegor256** [comment]
@rultor release, tag is `1.20`

**Pull request merged**
