### PR TITLE
#881 removed unnecessary types

### PR DESCRIPTION
**Pull request by krzyk**
#881 
* unnecessary types replaced with diamonds

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#883](https://github.com/yegor256/takes/issues/883) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#883](https://github.com/yegor256/takes/issues/883) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ae1bf38a-6e18-4acc-86c6-9755f869b711); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by krzyk** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#883](https://github.com/yegor256/takes/issues/883) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by g4s8** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@g4s8 thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/takes/issues/883#issuecomment-447029504))

@ypshenychka There is no quality review for [#883](https://github.com/yegor256/takes/issues/883), no performer

**Pull request merged**
