### PR TITLE
Update http status codes and descriptions

### PR DESCRIPTION
**Pull request by golszewski86**
* Added missing HTTP status codes (203, 205, 206, 300, 407, 409, 503, 504, 505)
* Status codes descriptions updated according to [RFC7231](https://tools.ietf.org/html/rfc7231) e.g. HTTP 302 is now "Found" instead of "Moved temporarily"
* Status codes ordered ascending so it's easier to visually find particular code

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#987](https://github.com/yegor256/takes/issues/987) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#987](https://github.com/yegor256/takes/issues/987) is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/42ec7fcc-f43c-46b1-9ae5-edf5972477ab); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/987#issuecomment-503813949))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#987](https://github.com/yegor256/takes/issues/987), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
This pull request [#987](https://github.com/yegor256/takes/issues/987) is assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/d704f0a0-661a-4f1a-858a-420991fc3219); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by golszewski86** [comment]
@paulodamaso @yegor256 ping

**Comment by paulodamaso** [comment]
@golszewski86 Thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#987](https://github.com/yegor256/takes/issues/987) is not in the agenda of @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (50 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#987](https://github.com/yegor256/takes/issues/987) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Pull request merged**
