### PR TITLE
issue #458

### PR DESCRIPTION
**Pull request by aschworer**
#458: Puzzle 377-e6ce369a (TkProxyTest.java - more tests) 
#430 TkRetry
@davvd please review

### CODE REVIEW

**Comment by davvd** [comment]
@aschworer Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@dmzaytsev it's yours, please review

**Comment by dmzaytsev** [comment]
@aschworer you have created one pull request for two issues, right?
if so I would suggest you to remove the code which relates to one of two issues and create another PR for it. Usually we create small pull requests, one issue - one PR

**Comment by aschworer** [comment]
@dmzaytsev will do

**Comment by aschworer** [comment]
@dmzaytsev would you advice the preferred way to do it? Is it better to make separate branches, or create one pull request and second one after the first is merged?

**Comment by dmzaytsev** [comment]
@aschworer are the issues independent of each other? If so I think it would better to make separate branches and create two pull requests in the one time

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is bad here as far as no code was merged here and new PRs were created instead.

**Comment by davvd** [comment]
> @davvd Quality is bad here as far as no code was merged here and new PRs were created instead.

@ypshenychka thank you very much

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @ypshenychka (for QA), payment ID is `72489361`

**Comment by aschworer** [comment]
@davvd @dmzaytsev Sorry for the delay. I have separated this pull request into two (for two separate issues) - #458 (pull request #471) and #430 (pull request #472). I've closed this pull request.

**Comment by davvd** [comment]
> @davvd @dmzaytsev Sorry for the delay. I have separated this pull request into two (for two separate issues) - #458 (pull request #471) and #430 (pull request #472). I've closed this pull request.

@aschworer OK

**Pull request closed without merging**
