### PR TITLE
#195 Wrong json linkedin user fields are used

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #195 

* changed fields to camel case according [Linkedin API docs, see Step 2 - Retrieve basic profile data](https://developer.linkedin.com/docs/signin-with-linkedin)

### CODE REVIEW

**Comment by davvd** [comment]
@dmzaytsev Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@darkled it's yours, please review

**Comment by darkled** [comment]
@rultor merge

**Comment by yegor256** [comment]
@dmzaytsev what about a test first?

**Comment by dmzaytsev** [comment]
@yegor256 Do you mean a test for PsLinkedin.parse() only?

**Comment by dmzaytsev** [comment]
@yegor256 no problem I can create  a test for PsLinkedin.parse()
but as far as I know we have a task #158 that should to do complex testing

**Comment by yegor256** [comment]
@dmzaytsev let's wait for that task first? and when it's done, you add your test for this particular problem

**Comment by dmzaytsev** [comment]
@yegor256 I guess a huge changes coming with #158... I suggest to make PsLinkedin.parse() public, create test for it and merge this PR. What do you think ?

**Comment by yegor256** [comment]
@dmzaytsev no. you never make methods public just to test them. it's anti-pattern, a terrible one

**Comment by dmzaytsev** [comment]
@yegor256 let's wait for  #158

**Comment by dmzaytsev** [comment]
@davvd @darkled  FYI

**Comment by yegor256** [comment]
@davvd we're waiting for #158 here

**Comment by davvd** [comment]
> @davvd we're waiting for #158 here

@yegor256 right, let's wait for #158

**Comment by dmzaytsev** [comment]
@yegor256 I saw that PsLinkedinTest implementation appeared in the master branch although #158 not completed yet.
I added a couple of tests for this task.
Take a look please

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by elenavolokhova** [comment]
@darkled
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review. We should get used to this rule as soon as possible.
Please confirm that you will try to find at least three problems next time.

**Comment by darkled** [comment]
@elenavolokhova I confirm, thank you

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@darkled I added 10 mins to @elenavolokhova (for QA review) in transaction 57160396; Much obliged! I have added **17 mins** to your account in payment "57160415", 406 hours and 59 mins spent; review comments (c=2) added as a bonus; +17 added to your rating, at the moment it is: [+2039](http://www.netbout.com/b/35091?open=rating)

**Pull request merged**
