### PR TITLE
refactor: Use try with resources instead of try-finally blocks

### PR DESCRIPTION
**Pull request by sandordargo**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#752` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandordargo thanks a lot!

**Comment by sandordargo** [comment]
@yegor256 you're welcome. I might create some small ones next week. Could you list my name as a contributor, maybe put a link to [my blog](http://sandordargo.com)?

**Comment by yegor256** [comment]
@sandordargo sure, just add yourself to the list in one of your next pull requests.

**Pull request merged**
