### PR TITLE
#884 Converting anonymous classes to lambda expressions

### PR DESCRIPTION
**Pull request by danilomo**
Only the following rule of thumb:

>   - You made a small amount of changes (less than 100 lines, less than 10 files)

was violated, due the large number of anonymous classes used in the project (specially in the test classes). The issue asked for getting rid of all of them.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#962](https://github.com/yegor256/takes/issues/962) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#962](https://github.com/yegor256/takes/issues/962) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/1affe1d2-6789-4f44-bbaa-9e40720f0c7b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by danilomo** [comment]
The code pushed didn't meet Quilce requirements. This task requires caution due the large number of files involved. Since I made a large number of changes without running Quilce after every file changed, I deleted the entire branch on my fork and I'll start again.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#962](https://github.com/yegor256/takes/issues/962) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by ypshenychka** [comment]
@danilomo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to the issue into PR's description.

**Comment by ypshenychka** [comment]
@danilomo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/takes/pull/962#issuecomment-462053064) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@fabriciofx Looks like you didn't have a chance to make code review here. Nevertheless I have to mark it as 'bad'. Agree?

**Comment by ypshenychka** [comment]
@danilomo ping

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/takes/issues/962#issuecomment-463551894))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
