### PR TITLE
For #984: Some of Guava replaced with Cactoos 

### PR DESCRIPTION
**Pull request by andreoss**
This is for #984

### CODE REVIEW

**Comment by andreoss** [comment]
@paulodamaso What do you think?

**Comment by paulodamaso** [comment]
@andreoss Sorry for the delay. I think it's good, I'll merge it

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1052` is not assigned, can't get performer

**Pull request merged**
