### PR TITLE
Bug #627 year check in LICENSE.txt

### PR DESCRIPTION
**Pull request by raphaelln**
Bug #627 year check in LICENSE.txt

**List of changes**

- **pom.xml**: included in package build phase the execution of **maven-verifier-plugin**, see more at https://maven.apache.org/plugins/maven-verifier-plugin.
- **verifier/verification.xml**: inclusion of verifications.xml file. This files contains the configuration of the verifier plugin. Test if the LICENSE.txt file contains years from 2014 to 2016, using the regex **\b20(?:1[4-6])\b**.

PS: Unfortunately this plugin doesn't support maven variables in **contains** tag. Just suport regex expressions.

### CODE REVIEW

**Comment by raphaelln** [comment]
@davvd Can you find someone to review it?

**Comment by davvd** [comment]
@raphaelln Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@raphaelln this should verify that the date is `2014-2016`, not that it is a year 2014 or 2015 or 2016

**Comment by raphaelln** [comment]
@krzyk I corrected the contains tag. 

In order to compile again I will have to update the LICENSE.txt from from *Copyright (c) 2015 Yegor Bugayenko* to *Copyright (c) 2014-2016 Yegor Bugayenko* and all java files, ok ?

**Comment by krzyk** [comment]
@raphaelln Yes, I think that was the intention of this issue.

**Comment by raphaelln** [comment]
@krzyk could you please review again ?

**Comment by krzyk** [comment]
@raphaelln could you also update years in:
```
src/it/file-manager/src/test/resources/log4j.properties
src/it/file-manager/src/main/resources/dir.xsl
src/it/file-manager/pom.xml
src/it/settings.xml
src/test/resources/log4j.properties
src/site/site.xml
pom.xml
```

**Comment by raphaelln** [comment]
@krzyk could you please review again ?

**Comment by krzyk** [comment]
@raphaelln why you did  dc487dd ? I assume it is a merge that went wrong

**Comment by raphaelln** [comment]
@krzyk done revert.

These files I changed because of missing of 2014-2016 header, I just change the header.
```
src/main/java/org/takes/facets/flash/TkFlash.java
src/main/java/org/takes/facets/fork/FkFixed.java
src/main/java/org/takes/facets/fork/FkHost.java
src/main/java/org/takes/rq/CapInputStream.java
src/main/java/org/takes/rq/RqMultipart.java
src/test/java/org/takes/facets/flash/TkFlashTest.java
src/test/java/org/takes/facets/fork/FkHostTest.java
src/test/java/org/takes/http/BkBasicTest.java
src/test/java/org/takes/http/MkSocket.java
src/test/java/org/takes/rq/CapInputStreamTest.java
```
Could you please review again ?

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by raphaelln** [comment]
@rultor @yegor256 @krzyk I merged with upstream again, @rultor could you try to merge again ?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@krzyk 10 mins was added to the account of @ypshenychka (for QA review), in transaction 80006802. I added **20 mins** to your account, many thanks for working with the project (80006851)! The completion time here was 213 hours and 59 mins.. review comments (c=5) added as a bonus. added +20 to your rating, now it is equal to [+6139](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
