### PR TITLE
#542 Add expiration date as a parameter.

### PR DESCRIPTION
**Pull request by t-izbassar**
Implementation for #542 .

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#789](https://github.com/yegor256/takes/issues/789) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#789](https://github.com/yegor256/takes/issues/789) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by t-izbassar** [comment]
@yegor256 ping)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3745](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9320](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#789](https://github.com/yegor256/takes/issues/789) is now out of scope

**Pull request merged**
