### PR TITLE
RsReturn validate location

### PR DESCRIPTION
**Pull request by t-izbassar**
Implementation of #353 according to this [SO Thread](https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#760` is now in scope, role is `REV`.

**Comment by 0crat** [comment]
Not enough funds available in the project

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#760](https://github.com/yegor256/takes/issues/760) is now out of scope

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to [@g4s8](http://www.0crat.com/u/g4s8), total is [+3040](http://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7375](http://www.0crat.com/u/yegor256)

**Pull request merged**
