### PR TITLE
#450 - RsXSLT.InClasspath.resolve() method cheks base parameter isEmpty()

### PR DESCRIPTION
**Pull request by danff**
#450 - RsXSLT.InClasspath.resolve() method checks base parameter is checked also with ifEmpty()

### CODE REVIEW

**Comment by davvd** [comment]
@danff Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@danff what about a unit test first? How do we know that your change actually is fixing anything?

**Comment by danff** [comment]
@yegor256 the fix was made in a prior pull request #474 which was already merged and closed. The unit test was also updated there to test different scenarios. But the issue author has asked to add base.isEmpty() check too. Even if URI class is accepting empty string in the ctor (where base parameter is used) and api javadoc explains what happens when different parts from URI are empty, I agree with author request about base.isEmpty().

**Comment by danff** [comment]
@yegor256 What will be the verdict for this pull request?

**Comment by danff** [comment]
@yegor256 sorry, closed by mistake

**Comment by danff** [comment]
@davvd @yegor256 any progress with the review?

**Comment by yegor256** [comment]
@danff what about a unit test? how do you know that the problem is solved?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
> @davvd @yegor256 any progress with the review?

@danff you should address your comments to the author of the ticket, always, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by simonjenga** [comment]
@danff Merged, OK.

**Comment by davvd** [comment]
@yegor256 Thanks so much! Your account was topped up for **17 mins** (transaction ID is `000-92335be6`, the task took 246 hours and 55 mins)... extra minutes for review comments (c=2)... +17 added to your rating, at the moment it is: [+7837](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
