### PR TITLE
For #1027: updating rultor image

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1027: updating rultor image

### CODE REVIEW

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1028` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
