### PR TITLE
#389: Fixed AppITCase

### PR DESCRIPTION
**Pull request by bdragan**
#389: Fixed AppITCase.

### CODE REVIEW

**Comment by davvd** [comment]
@bdragan Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-efdc59a4`, total time was 72 hours and 25 mins

extra minutes for review comments (c=1)

added +16 to your rating, now it is equal to [+12867](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
