### PR TITLE
#481 cleaner messages in failed tests in case of using HmRsStatus

### PR DESCRIPTION
**Pull request by exper0**
#481 cleaner messages in failed tests in case of using HmRsStatus

### CODE REVIEW

**Comment by davvd** [comment]
@exper0 Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@dmzaytsev it's yours,please review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by elenavolokhova** [comment]
@dmzaytsev 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@dmzaytsev paied 10 mins to @elenavolokhova for QA review (payment ID is `74031895`)... thanks, I just added **17 mins** to your account, payment `74031904`, 242 hours and 53 mins spent... review comments (c=2) added as a bonus... +17 added to your rating, at the moment it is: [+1518](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
