### PR TITLE
Status report for 2019-02-19

### PR DESCRIPTION
**Pull request by paulodamaso**
Status report for 2019-02-19

### CODE REVIEW

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#966](https://github.com/yegor256/takes/issues/966) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
This pull request [#966](https://github.com/yegor256/takes/issues/966) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/c82d7972-9a65-4f53-837a-bce105fe151c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/966#issuecomment-465131648))

@paulodamaso GitHub issue is still open, won't close

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@42de5f11-f7a4-4a2b-a41e-9a8cbe6aca06, thread: pool-3-thread-4
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/takes#966] declared for identity constraint of element "verbosity".
```

[0.41.15](https://github.com/zerocracy/farm): CID: [a1c4c87b-c3f8-4071-b29d-325bb6f7db61](https://www.0crat.com/footprint/C3FFK3YAY/a1c4c87b-c3f8-4071-b29d-325bb6f7db61), Type: "Close job"

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#966](https://github.com/yegor256/takes/issues/966) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by ypshenychka** [comment]
@fabriciofx Looks like no code review was done here at all, right?

**Comment by ypshenychka** [comment]
@fabriciofx ping

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad  ([here](https://github.com/yegor256/takes/issues/966#issuecomment-466769285))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
