### PR TITLE
#410: Documented Maven optional dependencies in the Readme

### PR DESCRIPTION
**Pull request by bdragan**
#410: Documented Maven optional dependencies in the Readme.

### CODE REVIEW

**Comment by davvd** [comment]
@bdragan Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@pinaf this pull request is for you, please review

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy

**Comment by elenavolokhova** [comment]
@pinaf 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by pinaf** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@pinaf 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 68534379... Much appreciated! **17 mins** was added to your account, payment ID `AP-0LN31143NW886792L`, time spent is 39 hours and 22 mins... you're getting extra minutes here (c=2)... added +17 to your rating, now it is equal to [+4174](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
