### PR TITLE
added jakarta namespace

### PR DESCRIPTION
**Pull request by PeJetuz**
@yegor256 
Hi!
Please review, I also create PR for [jcabi-parent](https://github.com/jcabi/jcabi-parent/pull/482).
I'm not really clear on whether I should add a dependency to the parent or whether it should only be in takes.
I also want to update the xml to the jakarta namespace.
[takes issue 1307](https://github.com/yegor256/takes/issues/1307)

### CODE REVIEW

**Comment by PeJetuz** [comment]
@yegor256 I updated the XML to the Jakarta namespace. Please review.
Thanks!

**Comment by yegor256** [comment]
@PeJetuz maven doesn't build

**Comment by PeJetuz** [comment]
@yegor256 Sorry, it's mine failed. I should have tested the build on jdk 11.
The artifact "jakarta.ws.rs:jakarta.ws.rs-api:4.0.0" is not compatible with JDK 11, only with 17 and later.
[Jakarta EE 11](https://jakarta.ee/specifications/platform/11/jakarta-platform-spec-11.0-m4#container-requirements):
`This specification requires that containers support execution in a Java™ runtime environment, as defined by the Java Platform, Standard Edition specification, v17 or later (Java SE 17 or later).`
I rolled back the version of this artifact to 3.1.0. Should I also create a new PR for jcabi-parent to downgrade this artifact?

**Comment by PeJetuz** [comment]
@yegor256 Is it possible to run the build again?
Thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@PeJetuz thanks!

**Pull request merged**
