### PR TITLE
#44 CcXOR is not tested

### PR DESCRIPTION
**Pull request by dmzaytsev**
For task #44 

added unit test for CcXOR

### CODE REVIEW

**Comment by davvd** [comment]
@dmzaytsev Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@krzyk review this one,please

**Comment by krzyk** [comment]
@dmzaytsev It is a good test, but it uses external class. It would be better to have a mock used instead of `CcPlain`.

**Comment by dmzaytsev** [comment]
@krzyk I removed external class
take a look please

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by dmzaytsev** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy now pls

**Comment by elenavolokhova** [comment]
@krzyk 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review. Try to find at least three problems next time.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by krzyk** [comment]
@elenavolokhova there was one issue found,  not zero. Besides that everything is clear.

**Comment by elenavolokhova** [comment]
@krzyk Yes, you are right, sorry for that.

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by krzyk** [comment]
@davvd did you forgot about me? :)

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @krzyk

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @krzyk 

@yegor256 I've paid 30 mins to @krzyk in transaction `55975921`

**Comment by davvd** [comment]
@krzyk just added 10 mins to @elenavolokhova (for QA), payment ID is `56003936`; Many thanks! **19 mins** were added to your account in Transaction ID `56003951` (task took 63 hours and 18 mins); extra minutes for review comments (c=4); +19 added to your rating, at the moment it is: [+5406](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
