### PR TITLE
Include Content-Length header from test requests

### PR DESCRIPTION
**Pull request by Happy-Neko**
Fix for ticket #463. Include Content-Length header from test requests.

### CODE REVIEW

**Comment by Happy-Neko** [comment]
@davvd Please proceed with code review.

**Comment by davvd** [comment]
@happy-neko Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@pinaf please review,thanks

**Comment by pinaf** [comment]
@Happy-Neko instead of manually adding the header to evry test, let's make RqFake set the header itself based on the body content lenth.

**Comment by Happy-Neko** [comment]
>  let's make RqFake set the header itself based on the body content lenth.

@pinaf `RqFake` has constructor:
````java
public RqFake(final List<String> head, final InputStream body)
````
It is impossible to know `InputStream`'s size in advance.

**Comment by pinaf** [comment]
@Happy-Neko You are correct.

**Comment by pinaf** [comment]
@rultor merge

**Comment by Happy-Neko** [comment]
@yegor256 Please confirm PR merge.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by pinaf** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@pinaf I added 10 mins to @ypshenychka (for QA review) in transaction 73951253. thanks, I just added **19 mins** to your account, payment `AP-5P63351382569561R`, 263 hours and 22 mins spent. you're getting extra minutes here (c=4). added +19 to your rating, now it is equal to [+5238](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
