### PR TITLE
#136 RqHeaders must be an interface

### PR DESCRIPTION
**Pull request by lauresh**
Refactored RqHeaders

### CODE REVIEW

**Comment by lauresh** [comment]
@longtimeago @davvd  I recreated pull request #191

**Comment by davvd** [comment]
@lauresh Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@longtimeago it's yours, please review

**Comment by longtimeago** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge this

**Comment by longtimeago** [comment]
@lauresh please merge from master

**Comment by lauresh** [comment]
@longtimeago merged

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by longtimeago** [comment]
@yegor256 can we try to merge again?

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by elenavolokhova** [comment]
@longtimeago 
- Please ask @lauresh to add the link to original issue to description, explain what was done in this PR.
- No issues were found in this PR. Try to find at least three issues next time.

**Comment by longtimeago** [comment]
@
*elenavolokhova <https://github.com/elenavolokhova> I'll try next time*

2015-05-04 10:32 GMT+02:00 ElenaV <notifications@github.com>:

> @longtimeago <https://github.com/longtimeago>
>
>    - Please ask @lauresh <https://github.com/lauresh> to add the link to
>    original issue to description, explain what was done in this PR.
>    - No issues were found in this PR. Try to find at least three issues
>    next time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yegor256/takes/pull/193#issuecomment-98634045>.
>



-- 
С уважением,
Павел

**Comment by lauresh** [comment]
@elenavolokhova 
#136
https://github.com/yegor256/takes/issues/136

**Comment by elenavolokhova** [comment]
@lauresh 
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Pull request description explains the solution proposed and contains a link to the original ticket it is related to.
 
 Pull request must briefly explain what was done in the branch, so that we can use this information later, for traceability. Please update the description itself with the link and more meaningful explanation about fix. It is not convenient to read all conversation here to find the link in the last comment.

**Comment by YamStranger** [comment]
@elenavolokhova description:
Problem described in ticket #136 :
RqHeaders must be an interface and its implementation must be in its nested class RqHeaders.Base. 
Solution:
RqHeaders now is interface, and its implementation now in nested class RqHeaders.Base. It is no behaving changes.

**Comment by elenavolokhova** [comment]
@YamStranger Thank you.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable

**Comment by davvd** [comment]
> @davvd Quality is acceptable

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@longtimeago I added 10 mins to @elenavolokhova (for QA review) in transaction 57186578. Thanks a lot, I just topped your account for **21 mins**, transaction ID `57186588`, total time was 192 hours and 45 mins. you're getting extra minutes here (c=6). +21 added to your rating, current score is: [+4474](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
