### PR TITLE
Status report 2019-12-05

### PR DESCRIPTION
**Pull request by paulodamaso**
Status report 2019-12-05

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1006](https://github.com/yegor256/takes/issues/1006) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@0crat out

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/1006#issuecomment-562164562))

@paulodamaso Job `gh:yegor256/takes#1006` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/1006#issuecomment-562164562))

@paulodamaso The job [#1006](https://github.com/yegor256/takes/issues/1006) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/1006#issuecomment-562164562))

@paulodamaso Pull request [#1006](https://github.com/yegor256/takes/issues/1006) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1006` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
