### PR TITLE
fix https://github.com/yegor256/takes/issues/945

### PR DESCRIPTION
**Pull request by Kartofanych**
move PqBaseMethod outside of parent interface
fix https://github.com/yegor256/takes/issues/945

### CODE REVIEW

**Comment by Kartofanych** [comment]
@yegor256 check please

**Comment by yegor256** [comment]
@Kartofanych what is the motivation for this? What problem are you trying to fix with these changes?

**Comment by Kartofanych** [comment]
> @Kartofanych what is the motivation for this? What problem are you trying to fix with these changes?
this is fix of issue https://github.com/yegor256/takes/issues/945
you asked to check issues that repository has - i found this one

**Comment by Kartofanych** [comment]
@yegor256 Any updates on this? (course is already finished)

**Comment by yegor256** [comment]
@Kartofanych the issue https://github.com/yegor256/takes/issues/945 was just a proposal, not an accepted bug (I closed it now). Please, look at the issues that are labeled as "bug" only

**Pull request closed without merging**
