### PR TITLE
[WIP][#744] FkHitRefresh now doesn't do IO inside constructors

### PR DESCRIPTION
**Pull request by skapral**
Fix for issue #744. Several concerns remain:

1. There are lots of other places where exceptions are thrown from constructor. I thought about marking them with puzzles but PDD doesn't accept them, saying that they are duplicates to each other (which is true, because the issue is the same everywhere).
2. Private class `HitRefreshHandle` was introduced, and there is one mutable field in there. It may have been eliminated by means of `StickyScalar` from Cactoos, but it is external dependency which is not allowed in Takes.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#745` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@skapral looks like something is wrong in your branch

**Comment by skapral** [comment]
@yegor256 I know, coverage degrades. Moreover, I am against my solution myself, there is one `null` property and one mutable class. I'm surprised you tried to merge it actually.

I'll think about it later, idea with StickyScalar seems to be perspective.

**Comment by 0crat** [comment]
The job [#745](https://github.com/yegor256/takes/issues/745) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/441434463). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/745#issuecomment-365292637))

@t-izbassar This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#745](https://github.com/yegor256/takes/issues/745) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 6mon
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) for [27min](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @skapral[/z](https://www.0crat.com/u/skapral): This user reported the ticket

**Comment by t-izbassar** [comment]
@yegor256 this job should bi in role `REV`, not `DEV`. I don't think I should do anything about it. Also this PR is pretty old. @skapral any plans to finish it?

**Comment by t-izbassar** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/745#issuecomment-365293628))

@t-izbassar The impediment for [#745](https://github.com/yegor256/takes/issues/745) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by skapral** [comment]
> @skapral any plans to finish it?
@t-izbassar This PR remained in work-in-progress state. I created it to check CI status. From that moment, I had no occasion to complete it.

The solution in this PR lacks two things:
1. Test coverage.
2. Eliminating `null`'s

The problem and solution seems still actual for now, but I have no time to complete these two points and I am not sure if puzzles are OK here (since absense of `null`'s is defined as key principle of the framework, probably @yegor256 will never pass it until they are eliminated). If puzzles are ok, then I can resolve the conflicts and complete this PR, but nothing more. Sorry.

**Comment by t-izbassar** [comment]
@skapral no probs. I was thinking of storing only `String`, so that we don't need to create `File` instance in constructor. However, we still need the `last` instance. Moreover, in `README.md` itself the example uses constructor with `String` which is no longer present. I think it's just outdated.

However, this will break public API I don't know what maintainers will think about it. So, the other possible one is to bring `Scalar` to the codebase and leave puzzle to replace `File` instances with those scalars. Or, as you mentioned you can finish this solution. But, if you have no time, I think you can just close this pr. The #744 issue is now assigned to me so I would need to finish it anyway somehow.

**Comment by yegor256** [comment]
@skapral if we get rid of NULL, this code may work.

**Comment by t-izbassar** [comment]
@skapral ping

**Comment by skapral** [comment]
> @skapral if we get rid of NULL, this code may work.

@t-izbassar @yegor256 ok, I resolved the conflicts and eliminated all `null`s I personally introduced. One `null`, introduced before me, still remains (function `directoryUpdated`) but I consider it out of this issue's scope. Will place puzzle on that.

**Comment by t-izbassar** [comment]
@yegor256 what should I do in this situation?
#744 assigned to me, however it is done by @skapral and he is not a member of Take afaik.
#745 also assigned to me, because the task has wrong scope. Should be `REV` and I don't have `REV` role.

If this PR is merged and issue closed, I will receive +60 points and monetary award. Maybe you want to reassign tasks.

**Comment by skapral** [comment]
@t-izbassar isn't it a cause for creating an issue to zerocrat? ;)

**Comment by t-izbassar** [comment]
> @t-izbassar isn't it a cause for creating an issue to zerocrat? ;)

@skapral yes, it is) it just could be clarified just in place. Will create one though, just to share experience with others, that might be in same situation.

**Comment by t-izbassar** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/745#issuecomment-366345887))

@yegor256 The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#745](https://github.com/yegor256/takes/issues/745), please stop working

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#745](https://github.com/yegor256/takes/issues/745) is now out of scope

**Pull request merged**
