### PR TITLE
#136 RqHeaders must be an interface

### PR DESCRIPTION
**Pull request by lauresh**
Refactored RqHeaders

@davvd Could you find a reviewer for this pull request ?

### CODE REVIEW

**Comment by davvd** [comment]
@lauresh Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@longtimeago review this one, please

**Comment by longtimeago** [comment]
@lauresh please, merge from master

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket was closed and new PR was opened instead. Quality of this one is bad.

**Comment by davvd** [comment]
> @davvd This ticket was closed and new PR was opened instead. Quality of this one is bad.

@elenavolokhova thanks for paying attention, the performer of this ticket won't be paid

**Comment by davvd** [comment]
@longtimeago just added 10 mins to @elenavolokhova (for QA), payment ID is `56015292`; done, I added **16 mins** in payment `56015309`, 25 hours and 46 mins spent to complete this; extra minutes for review comments (c=1); +16 added to your rating, at the moment it is: [+4723](http://www.netbout.com/b/35024?open=rating)

**Pull request closed without merging**
