### PR TITLE
For #902, removed all transient keywords.

### PR DESCRIPTION
**Pull request by oridan**
For #902, removed all transient keywords.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#964](https://github.com/yegor256/takes/issues/964) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#964](https://github.com/yegor256/takes/issues/964) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/eb17f298-bbcd-4fa3-994c-a335f337c1ff); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by oridan** [comment]
I just removed the key word "transient"  from files (private transient String xpto; -> private String xpto;) and then codecov failed.

@paulodamaso could you reduce codecov from 72.29% to 72.26%?

**Comment by oridan** [comment]
ping @fabriciofx

**Comment by oridan** [comment]
@fabriciofx ping

**Comment by oridan** [comment]
@fabriciofx ping

**Comment by oridan** [comment]
ping @fabriciofx

**Comment by oridan** [comment]
@paulodamaso could you review this PR?

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by paulodamaso** [comment]
@oridan thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/964#issuecomment-466665158))

@paulodamaso @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#964](https://github.com/yegor256/takes/issues/964), see [§21](http://www.zerocracy.com/policy.html#21); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#964](https://github.com/yegor256/takes/issues/964) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#964](https://github.com/yegor256/takes/issues/964) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
