### PR TITLE
Typo in attempt to correct typo

### PR DESCRIPTION
**Pull request by Tertioptus**
My apologies, there was indeed a grammatical error in the original text, but I created an error in my attempt to fix it.  This should resolve it.

### CODE REVIEW

**Comment by davvd** [comment]
@tertioptus I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@Tertioptus thanks!

**Comment by davvd** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-371cee89`, task took 2 hours and 52 mins to complete. you're getting extra minutes here (c=1). +16 added to your rating, current score is: [+4579](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
