### PR TITLE
Issue #485 (HmRsBody matcher for checking response body) implemented

### PR DESCRIPTION
**Pull request by rfqu**
Issue #485 fixed - HmRsBody matcher for checking response body implemented, and some tests created against the new class.

### CODE REVIEW

**Comment by davvd** [comment]
@rfqu I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@dmzaytsev it's yours, please review

**Comment by dmzaytsev** [comment]
@rfqu  please add description of what you did in the PR description, also include there reference to the issue you are fixing

**Comment by dmzaytsev** [comment]
@rfqu Travis CI build failed due to using unsupported features
> [ERROR] /home/travis/build/yegor256/takes/src/main/java/org/takes/facets/hamcrest/HmRsBody.java:[111,29] try-with-resources is not supported in -source 1.6
  (use -source 7 or higher to enable try-with-resources)

we should use Java 6 in this project

**Comment by dmzaytsev** [comment]
@rfqu please run full Maven build:
>$ mvn clean install -Pqulice

and fix checkstyle's issues

**Comment by dmzaytsev** [comment]
@rfqu Travis build failed. There are a few PMD violations.
please fix it

**Comment by dmzaytsev** [comment]
@rfqu please close the pull request if you don't want work on it anymore

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here. PR was not merged, so it can't be perfect, but CR followed all our rules and should be rewarded.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here. PR was not merged, so it can't be perfect, but CR followed all our rules and should be rewarded. 

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 77293465. **20 mins** was added to your account, many thanks for your contribution (payment 77293468)! The task took 431 hours and 36 mins.. you're getting extra minutes here (c=5). +20 added to your rating, current score is: [+3170](http://www.netbout.com/b/35166?open=rating)

**Pull request closed without merging**
