### PR TITLE
#755 Up to 2018, Happy New Year!

### PR DESCRIPTION
**Pull request by fabriciofx**
As per #755 .

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#756` is now in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#756` is now out of scope.

**Pull request merged**
