### PR TITLE
Construct RqHeaders.Smart from Request

### PR DESCRIPTION
**Pull request by Masynchin**
Remove unnecessary `new RqHeaders.Base(req)` calls if we construct `RqHeaders.Smart`.

### CODE REVIEW

**Comment by Masynchin** [comment]
@kerelape can you help me understand why CI complains?

**Review by kerelape — COMMENTED** [review]
Line 91 in PsBasic is 105 characters long, must be <= 100

**Comment by Masynchin** [comment]
@kerelape thanks!

**Comment by yegor256** [comment]
@Masynchin can you please submit modifications to the tests first, in a new pull request. Then, we merge them. After then, you will come up with modifications to the code. Now it's not clear whether your changes are valid. See https://www.yegor256.com/2022/08/04/code-and-tests-different-pull-requests.html

**Comment by Masynchin** [comment]
> See https://www.yegor256.com/2022/08/04/code-and-tests-different-pull-requests.html

@yegor256 I don't understand how this related to my changes. I am not adding new functionality or changing the current one, I only simplified the code without changing its logic.

**Comment by yegor256** [comment]
@Masynchin you modify both tests and live code at the same time. How do we know you are not cheating and not making tests pass with the new code?

**Comment by Masynchin** [comment]
> How do we know you are not cheating and not making tests pass with the new code?

By looking at code before/after my changes. Do replacing the constructor call counts as tests modification? I only replaced the use of first constructor to the second one.

https://github.com/yegor256/takes/blob/b6c88d2cb712b02f9a76fab6fb8667ad8f3bf2dd/src/main/java/org/takes/rq/RqHeaders.java#L190-L200

I won't open new PR only to apply the same simplification because it is in `test/`.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1135` is not assigned, can't get performer

**Pull request merged**
