### PR TITLE
#697 I updated qulice version. And fix warnings.

### PR DESCRIPTION
**Pull request by xupyprmv**
#697 I updated qulice version. I removed PMD.AvoidDuplicateLiterals suppression and add usage of diamond operator.

### CODE REVIEW

**Comment by davvd** [comment]
@xupyprmv Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@krzyk review this one,please

**Comment by krzyk** [comment]
@xupyprmv looks good (+1 for using latest qulice version :)

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by xupyprmv** [comment]
@yegor256 Please, review this PR.

**Comment by xupyprmv** [comment]
@yegor256 Please, review this PR.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by elenavolokhova** [comment]
@krzyk 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by krzyk** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@davvd  Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd  Quality is acceptable here.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@krzyk I added 10 mins to @elenavolokhova (for QA review) in transaction 97253157

thank you, added **18 mins** to your acc, payment num is `97253167`, 129 hours and 46 mins spent in total to complete

extra minutes for review comments (c=3)

+18 added to your rating, current score is: [+1350](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
