### PR TITLE
#540: Improve Javadoc in RsFlash

### PR DESCRIPTION
**Pull request by essobedo**
For #540 

The goal of this PR is to improve the Javadoc in RsFlash in order to:

- describe better what is "flash mechanism"
- provide more description than just "Ctor." for constructors with Throwable - focus mainly on how exception will be converted to text
- Provide information why it's better to use default cookie name
- Fix the code samples in Javadoc - they are confusing and not compilable
- Explain when you can use it and when it is not recommended

### CODE REVIEW

**Comment by davvd** [comment]
@essobedo I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@carlosmiranda please review,thanks

**Comment by essobedo** [comment]
@davvd Actually @mkordas was the initial reviewer of this issue, I just had to recreate the PR. The initial PR was https://github.com/yegor256/takes/pull/564

**Comment by mkordas** [comment]
@yegor256 can you assign me here so that I can finish review?

**Comment by yegor256** [comment]
@mkordas it's better to change the reviewer, especially in such situations

**Comment by mkordas** [comment]
@yegor256 OK, makes sense
@carlosmiranda please proceed

**Comment by davvd** [comment]
> @davvd Actually @mkordas was the initial reviewer of this issue, I just had to recreate the PR. The initial PR was https://github.com/yegor256/takes/pull/564

@essobedo it doesn't matter, we assign new reviewer to each new PR. we don't connect them

**Comment by carlosmiranda** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy

**Comment by elenavolokhova** [comment]
@carlosmiranda 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by mkordas** [comment]
@elenavolokhova I've found a few problems in the previous review for the same code

**Comment by elenavolokhova** [comment]
@mkordas Yes, I know. Thank you for pointing this. You were paid for your review. @carlosmiranda is a performer here and could not get a reward for your work. I consider this ticket as standalone entity.

**Comment by carlosmiranda** [comment]
@elenavolokhova confirmed, thanks

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@carlosmiranda I added 10 mins to @elenavolokhova (for QA review) in transaction 77261927

paid, thanks, added **17 mins** to your account, payment `77261938`, 98 hours and 42 mins was spent

you're getting extra minutes here (c=2)

+17 added to your rating, at the moment it is: [+2855](http://www.netbout.com/b/35023?open=rating)

**Pull request merged**
