### PR TITLE
Fix: RqMethod must be an interface #137

### PR DESCRIPTION
**Pull request by MohandAndel**
Convert RqMethod to interface .

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by davvd** [comment]
@darkled please review,thanks

**Comment by darkled** [comment]
@MohandAndel there are 14 qulice violations:
```
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[46]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[51]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[56]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[61]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[66]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[71]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[76]: Two consecutive empty lines (RegexpMultilineCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[76]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[84]: Two consecutive empty lines (RegexpMultilineCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[84]: Redundant 'public' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[87]: First sentence in a comment should start with a capital letter (RegexpMultilineCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[106]: Parameter req should be final. (FinalParametersCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[111]: Redundant 'final' modifier. (RedundantModifierCheck)
[ERROR] /src/main/java/org/takes/rq/RqMethod.java[116]: Redundant 'final' modifier. (RedundantModifierCheck)
```

Could you please fix them?

**Comment by MohandAndel** [comment]
I try to pass the 2 checks , but it ask me to remove "final" from the constants in the interface , is that ok ?
Or these constants should be removed somewhere else .

**Comment by darkled** [comment]
@MohandAndel since interface is just a contract and cannot have state or behavior, every field is implicitly both `static` and `final`, so there is no need in these modifiers, you can remove it.

**Comment by darkled** [comment]
@MohandAndel there are still some violations as well merge conflicts:
```
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[33]: Empty line or comment between imports is not allowed (ImportCohesionCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[66]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[102]: Line is longer than 80 characters (found 83). (LineLengthCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[111]: Line is longer than 80 characters (found 90). (LineLengthCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[113]: operator new rparen at indentation level 24 not at correct indentation, 20 (IndentationCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[119]: Line is longer than 80 characters (found 81). (LineLengthCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[121]: operator new rparen at indentation level 24 not at correct indentation, 20 (IndentationCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[147]: Line is longer than 80 characters (found 81). (LineLengthCheck)
[ERROR] /src/main/java/org/takes/rq/RqCookies.java[151]: Line is longer than 80 characters (found 83). (LineLengthCheck)
```

Also, when you change something please notify reviewer with a message in order to get quicker feedback

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@darkled @yegor256 This ticket has a lot of issues and finally provides no solution at all. The quality is bad and I consider that it shouldn't be paid. Correct me if I'm wrong, please.

**Comment by elenavolokhova** [comment]
@davvd Quality of this ticket is bad.

**Comment by davvd** [comment]
> @davvd Quality of this ticket is bad.

@elenavolokhova thanks a lot, noticing bad quality is what makes us better

**Comment by davvd** [comment]
@darkled I added 10 mins to @elenavolokhova (for QA review) in transaction 55998884; Much obliged! I have added **18 mins** to your account in payment "55998894", 71 hours and 30 mins spent; review comments (c=3) added as a bonus; added +18 to your rating, now it is equal to [+2295](http://www.netbout.com/b/35091?open=rating)

**Pull request closed without merging**
