### PR TITLE
Typo RqPring -> RqPrint

### PR DESCRIPTION
**Pull request by mvpotter**

### CODE REVIEW

**Comment by davvd** [comment]
@mvpotter Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@mvpotter thanks!

**Comment by davvd** [comment]
@yegor256 thank you, added **16 mins** to your acc, payment num is `000-f110e2fc`, 193 hours and 16 mins spent in total to complete... extra minutes for review comments (c=1)... +16 added to your rating, at the moment it is: [+52](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
