### PR TITLE
Use `cactoos.InputOf`

### PR DESCRIPTION
**Pull request by Masynchin**
Sorry, but I haven't run any tests. I'm not Java programmer, but I think this changes makes this code more Java-way.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by Masynchin** [comment]
@yegor256 sorry for conflicting PR. I changed exception type in order to use `InputOf(...).stream()` and now it doesn't show any errors. `mvn clean install -Pqulice` raises error but for `RsFailure`, which I doesn't change. CI successfully builds my branch.

**Comment by yegor256** [comment]
@Masynchin thanks!

**Comment by Masynchin** [comment]
@yegor256 I search through Takes and Cactoos source code and found [`InputStreamOf`](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/io/InputStreamOf.java). This is more low-level class than `InputOf`? It seems that `new InputStreamOf(...)` more suitable here than `new InputOf(...).stream()`.

I can open new PR that replaces `InputOf` to `InputStreamOf`. I also want to replace all `Files.newInputStream(file.toPath())` to `new InputStreamOf(file)`. I can't do it with `new InputOf(file).stream()` because it raises more generic `Exception` instead of `IOException`, but can with `InputStreamOf`. I am not sure about that since I am not an expert in Java, but it seems to work.

**Pull request merged**
