### PR TITLE
(#1025) Updated cactoos dependency to version 0.44

### PR DESCRIPTION
**Pull request by fanifieiev**
This PR is for #1025

### CODE REVIEW

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by fanifieiev** [comment]
@paulodamaso Please try merging again

**Comment by paulodamaso** [comment]
@fanifieiev done!

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1033` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
