### PR TITLE
#101: Added toString to Takes and Responses.

### PR DESCRIPTION
**Pull request by bdragan**
This PR contains the implementation of `toString` methods in `Take` and `Response` classes, as described in the issue #101.

### CODE REVIEW

**Comment by davvd** [comment]
@bdragan Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@pinaf it's yours,please review

**Comment by pinaf** [comment]
@bdragan what issue does this PR fix? Please add a reference to the issue in your first comment. Also, please explain a bit what was done in your first comment.

**Comment by pinaf** [comment]
@rultor merge

**Comment by bdragan** [comment]
@pinaf Thanks for the review; I updated the first comment.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by bdragan** [comment]
@davvd, @yegor256 
`Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector`

Seems like test infrastructure issue. I suggest creating an issue for somebody to look at it.

**Comment by pinaf** [comment]
@yegor256 just in case it is intermittent. we could try the merge again.

**Comment by yegor256** [comment]
@bdragan why suggesting to create an issue, instead of creating it? :)

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by bdragan** [comment]
@yegor256 I agree, the issue #401 created. :)

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by bdragan** [comment]
@pinaf @yegor256 Since #403 is fixed, could you please trigger the merge again? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by pinaf** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@pinaf 10 mins was added to the account of @ypshenychka (for QA review), in transaction 67489274... I just added **20 mins** to your account, many thanks for your contribution (AP-9SB9710087272174H).. 309 hours and 30 mins spent here... review comments (c=5) added as a bonus... +20 to your rating, your total score is [+4194](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
