### PR TITLE
(#1024) Invalid request line

### PR DESCRIPTION
**Pull request by baudoliver7**
- Update `RqFake`
- Update `RqFake` test

Close: #1024

### CODE REVIEW

**Comment by andreoss** [comment]
@baudoliver7 Tests are failing

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@baudoliver7 something is wrong with your branch, I believe

**Comment by baudoliver7** [comment]
@yegor256 Ok, let me take a look please.

**Comment by baudoliver7** [comment]
@yegor256 Good to merge now :)

**Comment by yegor256** [comment]
@baudoliver7 why 107 files updated? Something is wrong with the branch?

**Comment by baudoliver7** [comment]
@yegor256 Ooops! You are right. It is a bad manipulation at the beginning of the task.
Let's me clean the branch.

**Comment by baudoliver7** [comment]
@yegor256 branch cleaned :)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (299 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by sereshqua** [comment]
@andreoss please make sure you will find at least 3 issues during next CR, thanks

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
