### PR TITLE
For #832: Added test to `describeTo` method.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #832: 
- Added test to `describeTo` method.
- Updated `appveyor.tml` with correct java version.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#857](https://github.com/yegor256/takes/issues/857) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#857](https://github.com/yegor256/takes/issues/857) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2811416152); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 Please take a look. Also, I don't know why codecov started complaining about code that I didn't even touched

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@g4s8 please take a look. Codacy complains that "JUnit tests should include assert() or fail()", but we are using `MatchersAssert.assertThat` in our tests, so every test we add it fails on codacy beacause a new issue is added. Please review the PR disregarding this codacy failure.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#857](https://github.com/yegor256/takes/issues/857) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
> The code reviewer found at least three problems in the code 

Only one issue waas found during this review.
Please, confirm that you will try to find at least three issues next time.

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
