### PR TITLE
For #968. Removing Guava's code.

### PR DESCRIPTION
**Pull request by zCRUSADERz**
For #968
- Updated cactoos-matchers to 0.15
- Replaced Guava's code on cactoos
- Replaced statis matchers on cactoos-matchers
- Updated puzzle

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#979](https://github.com/yegor256/takes/issues/979) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#979](https://github.com/yegor256/takes/issues/979) is assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/a38ddc14-1068-4d21-9f40-4c7a88ccb95c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#979](https://github.com/yegor256/takes/issues/979) is now out of scope

**Comment by 0crat** [comment]
Pull request [#979](https://github.com/yegor256/takes/issues/979) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@Serranya did you make code review at all? I don't see your comments and also i don't see these problems fixed;  @zCRUSADERz am I missing smth?

**Comment by zCRUSADERz** [comment]
@sereshqua I have not fully studied the problem, so I closed the PR until I correct the shortcomings

**Comment by sereshqua** [comment]
@zCRUSADERz The job is closed only when the reported problem is solved

**Comment by sereshqua** [comment]
@0crat quality good bad

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +25 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by zCRUSADERz** [comment]
@sereshqua I thought to reopen PR when I correct the shortcomings. Now I need to open a new PR?

**Comment by sereshqua** [comment]
@zCRUSADERz oops, i just noticed TYPO in quality result, it should have been bad; I believe new issue needs to be opened if this is not solved

**Comment by Serranya** [comment]
@sereshqua I did not do a quality review. The PR was retracted before that.

**Comment by sereshqua** [comment]
@Serranya well, then it is a zerocrat bug... it was assigned to me to check your work

**Pull request closed without merging**
