### PR TITLE
RsHTML changed to RsHtml in readme.md

### PR DESCRIPTION
**Pull request by pchmielowski**
I have corrected the typo in usage instruction.

### CODE REVIEW

**Comment by davvd** [comment]
@pchmielowski Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@pchmielowski thanks!

**Comment by davvd** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-fa72241e`, task took 105 hours and 9 mins to complete

review comments (c=1) added as a bonus

+16 added to your rating, current score is: [+252](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
